### ISSUE TITLE
String could not find any enabled regions

### ISSUE THREAD

**Issue by interrupted** [gruntwork-io/cloud-nuke#102]
Hi,
I try to run cloud-nuke aws --resource-type ec2 --dry-run.
I have configured env variables:
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
AWS_REGION.
I do not have aws cli installed.

When running I get the error message:
*errors.errorString could not find any enabled regions
/go/src/github.com/gruntwork-io/cloud-nuke/aws/aws.go:64 (0x85fd15e)
/go/src/github.com/gruntwork-io/cloud-nuke/aws/aws.go:77 (0x85fd1ae)
/go/src/github.com/gruntwork-io/cloud-nuke/commands/cli.go:128 (0x860fd5f)
/go/src/github.com/gruntwork-io/cloud-nuke/vendor/github.com/gruntwork-io/gruntwork-cli/errors/errors.go:93 (0x84d8343)
/go/src/github.com/gruntwork-io/cloud-nuke/vendor/github.com/urfave/cli/app.go:490 (0x84cabc2)
/go/src/github.com/gruntwork-io/cloud-nuke/vendor/github.com/urfave/cli/command.go:210 (0x84cbb48)
/go/src/github.com/gruntwork-io/cloud-nuke/vendor/github.com/urfave/cli/app.go:255 (0x84c93db)
/go/src/github.com/gruntwork-io/cloud-nuke/vendor/github.com/gruntwork-io/gruntwork-cli/entrypoint/entrypoint.go:21 (0x8611971)
/go/src/github.com/gruntwork-io/cloud-nuke/main.go:13 (0x8611b99)
/usr/local/go/src/runtime/proc.go:195 (0x807010d)
/usr/local/go/src/runtime/asm_386.s:1635 (0x8096351)
  error="could not find any enabled regions"

I tried to follow https://github.com/gruntwork-io/cloud-nuke/issues/49
but I can't get the repo mentioned.
Could any one help me with this?
Thanks, Agata

**Comment by interrupted** [comment]
Hi again,
Could I request any support for this?
Thanks,
Agata

**Comment by saurabh-hirani** [comment]
Hi @interrupted,

As per the discussion in the https://github.com/gruntwork-io/cloud-nuke/issues/49 - can you try the following:

1. Install aws cli and ensure that aws cli is working before using cloud nuke - just to verify that you don't have any aws cli related issues. Doing a simple `aws s3 ls` will help you check any buckets in your account  or `aws ec2 describe-instances` to list instances.

2. If the binary is not working - can you follow instructions in https://github.com/gruntwork-io/cloud-nuke/issues/77 and see if setting up local dev env works? 

There is no clear way to reproduce the issue you are facing as the previous user who faced the issue got a workaround by using the local dev env mentioned in step 2. Having a docker image with a pre-built `cloud-nuke` and trying it out might isolate the issue to see if it is tied to your machine setup.

**Comment by interrupted** [comment]
Hi,
I tried again with exported variables and it worked without AWS CLI both from linux local machine and pipeline also - it must have been my misconfiguration - thanks anyway for the support.
Agata
