### ISSUE TITLE
Allow specifying exclusion tags

### ISSUE THREAD

**Issue by yorinasub17** [gruntwork-io/cloud-nuke#103]
The new s3 nuking capability has a built in mechanism to ignore any buckets that have the tag `cloud-nuke-excluded`. We should consider extending this to other resources.

See https://github.com/gruntwork-io/cloud-nuke/pull/101#discussion_r402139387 for more context and suggestions.

**Comment by aaronsteers** [comment]
FYI (related): I filed a spec proposal at #109 which would add global tag-based resource exclusion as an option.

**Comment by hongil0316** [comment]
The exclusion tag has been implemented here https://github.com/gruntwork-io/cloud-nuke/pull/570. Closing this PR.
