### ISSUE TITLE
What IAM permissions are required for cloud-nuke ?

### ISSUE THREAD

**Issue by queglay** [gruntwork-io/cloud-nuke#106]
Great tool!  I'm wondering is there any documentation on the required permissions to run cloud-nuke?

currently I get 
```
...is not authorized to perform: ecs:ListClusters on resource: *\n\tstatus code: 400,
```
which I can fix, but would be cool to know the prerequisite permissions in any case.

**Comment by saurabh-hirani** [comment]
The error you see is not tied to cloud-nuke but to AWS permissions i.e. the credentials with which you are running cloud-nuke - does not have permissions to list ecs clusters. You could:

1. Use credentials which grant you ecs:* access.
2. Exclude ecs from nuking by specifying the `--exclude-resource-type ecs` from the list as per https://github.com/gruntwork-io/cloud-nuke/blob/master/README.md

**Comment by queglay** [comment]
Thanks!  Using includes was the solution for me here!
