### ISSUE TITLE
cloud-nuke aws --exclude-resource-type s3 --dry-run NOT SUPPORTED

### ISSUE THREAD

**Issue by interrupted** [gruntwork-io/cloud-nuke#107]
Hi,
When running:

cloud-nuke aws --exclude-resource-type s3 --dry-run
Incorrect Usage: flag provided but not defined: -exclude-resource-type

NAME:
   cloud-nuke aws - BEWARE: DESTRUCTIVE OPERATION! Nukes AWS resources (ASG, ELB, ELBv2, EBS, EC2, AMI, Snapshots, Elastic IP, RDS).

USAGE:
   cloud-nuke aws [command options] [arguments...]

OPTIONS:
   --region value          regions to include
   --exclude-region value  regions to exclude
   --resource-type value   Resource types to nuke
   --list-resource-types   List available resource types
   --older-than value      Only delete resources older than this specified value. Can be any valid Go duration, such as 10m or 8h. (default: "0s")
   --dry-run               Dry run without taking any action.
   --force                 Skip nuke confirmation prompt. WARNING: this will automatically delete all resources without any confirmation

ERRO[2020-04-06T21:50:27Z] flag provided but not defined: -exclude-resource-type  error="flag provided but not defined: -exclude-resource-type"

Like in the title, unfortunately, this is not working as described in the WIKI.
Thanks,
Agata

**Comment by yorinasub17** [comment]
Which version of `cloud-nuke` are you using? This was introduced in https://github.com/gruntwork-io/cloud-nuke/releases/tag/v0.1.17

**Comment by brikis98** [comment]
No response in a few months, so closing.
