### ISSUE TITLE
Add support for more complex matching rules

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/cloud-nuke#108]
We have many clean-up use cases where we want to nuke all resources that match a specific pattern: e.g., nuke S3 buckets, IAM roles, and IAM profiles where the name matches one of a long list of specific regular expressions (i.e., those that come from our automated tests).

We should extend cloud-nuke with a way to filter resources using these match rules. Specifying them via CLI arguments is likely going to be inconvenient, so we may need some config format for this.

**Comment by aaronsteers** [comment]
I totally agree this would be valuable. 

Related issue (not started): #88

**Comment by rhoboat** [comment]
The first version of this is merged: #113 **Add config option for complex matching against s3 buckets**

**Comment by marinalimeira** [comment]
@brikis98 was this addressed when adding the config file? Can we close this one?

**Comment by brikis98** [comment]
Yup, closing.
