### ISSUE TITLE
EKS nuke should take into account fargate profiles

### ISSUE THREAD

**Issue by yorinasub17** [gruntwork-io/cloud-nuke#111]
Since you can't destroy an EKS cluster with fargate profiles, the nuking fails. This is a request to also delete fargate profiles on the EKS cluster prior to destroying the cluster.

**Comment by DMEvanCT** [comment]
Looking into this.

**Comment by yorinasub17** [comment]
Fixed in https://github.com/gruntwork-io/cloud-nuke/releases/tag/v0.7.0
