### ISSUE TITLE
Feature Request: add ability to delete users, groups, and policies

### ISSUE THREAD

**Issue by queglay** [gruntwork-io/cloud-nuke#116]
For each deployment and test I create new users, with a pipeline id in the user name, since tags can't be used.

It would be awesome if we could use a regex to clean out resources like users if they matched.

**Comment by brikis98** [comment]
A PR to add support for deleting IAM resources (users, groups, policies) is welcome. See also https://github.com/gruntwork-io/cloud-nuke/issues/108 for more ability to match on regex and other more complex patterns.

**Comment by marinalimeira** [comment]
As of today, we have the ability to nuke IAM Users and they can be filtered using the config file. I am leaving this issue open because we still don't support IAM Groups and Policies.

**Comment by queglay** [comment]
A great step nonetheless, thanks!
