### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by chenrui333** [gruntwork-io/cloud-nuke#117]
Just FYI, I have added one formula for this tool in the homebrew side (https://github.com/Homebrew/homebrew-core/pull/55228)

**Comment by brikis98** [comment]
Nice, thanks! Looks like that PR is closed though?

**Comment by chenrui333** [comment]
@brikis98 yeah, I need a new release to kick if off again (not sure if you can make one anytime soon :) )

**Comment by chenrui333** [comment]
Currently, it failed with audit failure.

```
==> brew audit --skip-style cloud-nuke --online --new-formula
==> FAILED
Error: undefined local variable or method `created_pr_comment' for Homebrew:Module
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:148:in `audit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
cloud-nuke:
  * Formulae should not require patches to build. Patches should be submitted and accepted upstream first.
```

**Comment by chenrui333** [comment]
@brikis98 if possible, can I get a new release so that I can proceed with the homebrew formula? This would be a great tool for lots of homebrew users.

**Comment by brikis98** [comment]
Done! Binaries should show up shortly. https://github.com/gruntwork-io/cloud-nuke/releases/tag/v0.1.19

**Comment by chenrui333** [comment]
thanks, I will resume what I did.

**Comment by chenrui333** [comment]
Made a new one https://github.com/Homebrew/homebrew-core/pull/55559

**Comment by chenrui333** [comment]
Have merged homebrew-core PR for a while.

Here is my installation log for the brew formula.
```
==> Downloading https://homebrew.bintray.com/bottles/cloud-nuke-0.1.20.mojave.bottle.tar.gz
Already downloaded: /Users/rchen/Library/Caches/Homebrew/downloads/52c0b8a5380156c4566a6117ac0677d4bfbcb603c98d4d2fbbeb91c976ef1d6d--cloud-nuke-0.1.20.mojave.bottle.tar.gz
==> Pouring cloud-nuke-0.1.20.mojave.bottle.tar.gz
==> Caveats
Before you can use these tools, you must export some variables to your $SHELL.
  export AWS_ACCESS_KEY="<Your AWS Access ID>"
  export AWS_SECRET_KEY="<Your AWS Secret Key>"
  export AWS_REGION="<Your AWS Region>"
==> Summary
🍺  /usr/local/Cellar/cloud-nuke/0.1.20: 5 files, 29.8MB
```

With that being said, closing this issue tracker. Thanks!
