### ISSUE TITLE
Does not support cn-north-1, cn-northwest-1 region

### ISSUE THREAD

**Issue by tonghuaroot** [gruntwork-io/cloud-nuke#126]
Hi Team,
In https://github.com/gruntwork-io/cloud-nuke/blob/c0ace864cfa23aecbd0efff93a4a382ee0b532f1/aws/aws.go#L23 ,I found it not support China Region(cn-north-1, cn-northwest-1),if use this need to do some fix.
Do you have any plan do support China Region(cn-north-1, cn-northwest-1)?

**Comment by brikis98** [comment]
We do not currently use those regions (not even sure our AWS accounts have access to them?), so we have not looked into what it would take to add support for them. Any idea what's involved?

**Comment by omg2hei** [comment]
China region and global region are completely independent. There is no way to use the services of the China region by using a global region account. Consider applying for an account in China Region.

**Comment by jonjohnston** [comment]
Why was this closed? This seems to be a reasonable request. What is the difficulty with enabling china partition?
