### ISSUE TITLE
New feature: ability to delete IAM roles 

### ISSUE THREAD

**Issue by zackproser** [gruntwork-io/cloud-nuke#131]
To assist with hitting the IAM roles limit in AWS - we could use the ability to delete IAM roles - but to also provide a list of roles that should be preserved and not deleted.

**Comment by brikis98** [comment]
I think we'd want to support specifying regular expressions for which IAM roles to delete via the config file.

**Comment by byarbrough** [comment]
Related to #116, which addresses IAM users and policies

**Comment by ina-stoyanova** [comment]
@zackproser I see you've had some thoughts here and assigned @rhoboat. I wonder what's the latest on this issue? Is there any action for us to take?

**Comment by zackproser** [comment]
@ina-stoyanova Hmm, from looking through internal messages it seems we initially were planning to use this one as a trial project? I'm not sure now why I assigned it to Rho - unless they were going to take a look at this?

**Comment by zackproser** [comment]
Support for IAM Roles and regex matching via config file were added in https://github.com/gruntwork-io/cloud-nuke/pull/330
