### ISSUE TITLE
Cloud-nuke exclude

### ISSUE THREAD

**Issue by aizada92** [gruntwork-io/cloud-nuke#138]
Hey! is there any example yml files where you use exclude for cloudnuke? for some reason, our regex for ecsserv is not picking up. Working fine for s3, but not working for ecsserv and eip?

**Comment by brikis98** [comment]
We only have preliminary support for the config file and regex format so far: https://github.com/gruntwork-io/cloud-nuke#whats-supported. So, unfortunately, ECS is not going to work yet.
