### ISSUE TITLE
Update cloud-nuke config to delete S3 buckets in Gruntwork Phx DevOps accounts

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/cloud-nuke#139]
We shouldn't delete ALL buckets in that account, as some _might_ still be important (Acme? Analytics? Training? Terraform Up & Running stuff?), so we should specify it using a filter that specifies specific regex patterns. See [here for starting patterns](https://github.com/gruntwork-io/prototypes/blob/master/aws-gc/aws-gc.py#L517-L520).

**Comment by ina-stoyanova** [comment]
This looks like it's been done. https://github.com/gruntwork-io/cloud-nuke/blob/master/.circleci/nuke_config.yml#L3-L16. Thanks, Yori!
