### ISSUE TITLE
cloud-nuke tests failing to clean up S3 buckets

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/cloud-nuke#140]
Our Phx DevOps account is accumulating a bunch of `cloud-nuke-test-xxx` buckets... Something in the tests must be failing to do clean up. Note that #135 made a change to the S3 code recently, so perhaps it's related to that?

**Comment by ina-stoyanova** [comment]
After syncing up with @yorinasub17 & @infraredgirl, we've agreed that the cause (as pointed by @yorinasub17 above, and after some investigation this afternoon) is the lack of cleanup of S3 buckets after testing S3 buckets creation with invalid bucket args. 

We agreed to revert the change.

**Comment by ina-stoyanova** [comment]
^ PR above fixes this 👍
