### ISSUE TITLE
[CLI] Allow dropping `--resource-type`

### ISSUE THREAD

**Issue by rhoboat** [gruntwork-io/cloud-nuke#153]
Issue
-----
Tools like the AWS CLI allow you specify a resource type without any flags, such as `aws eks --blah-blah` and `aws s3 ls`. In these commands `eks` and `s3` are resource types, but you don't need any flags to say so.

Suggestion
-----------
Could we allow a syntax like `cloud-nuke aws eks ...` and `cloud-nuke aws s3 ... `? This would ease the _mental_ transition between using our tool and using the AWS CLI, and it also means less typing.

* `cloud-nuke aws s3 eks ec2 ... ` would mean nuke all of these resource types. Beats writing out `--resource-type s3 --resource-type ekscluster --resource-type ec2` (that alone was annoying to type here!).

**Comment by DMEvanCT** [comment]
You might want to continue to use the flag but add a parser after? --resource-type ekscluster,ec2,rds?

**Comment by hongil0316** [comment]
Closing this ticket since we had no activies in this ticket for the past 3 years.
