### ISSUE TITLE
Delete DHCP scopes

### ISSUE THREAD

**Issue by RockAfeller2013** [gruntwork-io/cloud-nuke#156]
Please add deleting all DHCP Scopes

**Comment by DMEvanCT** [comment]
Are you referring to DHCP option set? If I can get some background on this I can take a look

**Comment by ina-stoyanova** [comment]
@RockAfeller2013 a bump  here. It would be useful to know what's the use case for you as @DMEvanCT has suggested :)

**Comment by hongil0316** [comment]
The change for this has been submitted recently. Closing this issue - https://github.com/gruntwork-io/cloud-nuke/pull/610
