### ISSUE TITLE
Error nuking us-gov (govcloud) regions

### ISSUE THREAD

**Issue by gr8sk8s** [gruntwork-io/cloud-nuke#157]
Get the following error right off the bat ("could not find any enabled regions") when trying to nuke Govcloud (us-gov-west-1) resources: 

❯ cloud-nuke aws --region us-gov-west-1
INFO[2020-11-30T20:13:22-05:00] The following resource types will be nuked:
INFO[2020-11-30T20:13:22-05:00] - ami
INFO[2020-11-30T20:13:22-05:00] - asg
INFO[2020-11-30T20:13:22-05:00] - ebs
INFO[2020-11-30T20:13:22-05:00] - ec2
INFO[2020-11-30T20:13:22-05:00] - ecscluster
INFO[2020-11-30T20:13:22-05:00] - ecsserv
INFO[2020-11-30T20:13:22-05:00] - eip
INFO[2020-11-30T20:13:22-05:00] - ekscluster
INFO[2020-11-30T20:13:22-05:00] - elb
INFO[2020-11-30T20:13:22-05:00] - elbv2
INFO[2020-11-30T20:13:22-05:00] - lambda
INFO[2020-11-30T20:13:22-05:00] - lc
INFO[2020-11-30T20:13:22-05:00] - rds
INFO[2020-11-30T20:13:22-05:00] - s3
INFO[2020-11-30T20:13:22-05:00] - snap
ERRO[2020-11-30T20:13:34-05:00] *errors.errorString **could not find any enabled regions**
github.com/gruntwork-io/cloud-nuke/aws/aws.go:66 (0x1972488)
github.com/gruntwork-io/cloud-nuke/aws/aws.go:79 (0x1972566)
github.com/gruntwork-io/cloud-nuke/commands/cli.go:200 (0x19913ce)
github.com/gruntwork-io/gruntwork-cli@v0.1.2/errors/errors.go:93 (0x16a019e)
github.com/urfave/cli@v1.20.0/app.go:490 (0x168fe42)
github.com/urfave/cli@v1.20.0/command.go:210 (0x16910db)
github.com/urfave/cli@v1.20.0/app.go:255 (0x168e028)
github.com/gruntwork-io/gruntwork-cli@v0.1.2/entrypoint/entrypoint.go:21 (0x1993e78)
github.com/gruntwork-io/cloud-nuke/main.go:13 (0x19940a7)
runtime/proc.go:204 (0x1039609)
runtime/asm_amd64.s:1374 (0x106b861)
  **error="could not find any enabled regions"**

FYI, this is cloud-nuke binary on mac (via brew install).  The version is : 
❯ cloud-nuke -v
cloud-nuke version v0.1.24

BTW, this tool works just fine in commercial regions.  Just not in Govcloud. Any plans to support the us-gov-*  regions?

**Comment by brikis98** [comment]
We'd love to support govcloud, but don't have bandwidth to do it right now. If anyone has time available, a PR is welcome!

**Comment by yrral86** [comment]
I believe this is the same issue as https://github.com/gruntwork-io/cloud-nuke/issues/132

**Comment by marinalimeira** [comment]
This was solved by #179. Closing the issue :)
