### ISSUE TITLE
Not accurate number of AMIs deleted

### ISSUE THREAD

**Issue by hposca** [gruntwork-io/cloud-nuke#161]
In [ami.go](https://github.com/gruntwork-io/cloud-nuke/blob/master/aws/ami.go) `imageIds` is the parameter passed to the [`nukeAllAMIs`](https://github.com/gruntwork-io/cloud-nuke/blob/master/aws/ami.go#L43) function and it is used [at the end]((https://github.com/gruntwork-io/cloud-nuke/blob/master/aws/ami.go#L66)) as `len(imageIds)` to inform the number of AMIs deleted but `imageIds` is never updated so it does not represent the images that were actually deleted.

**Comment by brikis98** [comment]
Good catch. PR to fix this is welcome!

**Comment by ina-stoyanova** [comment]
This issue seems resolved. Closing!
