### ISSUE TITLE
Be consistent about nuking behavior across resources

### ISSUE THREAD

**Issue by yorinasub17** [gruntwork-io/cloud-nuke#162]
Some resources like AWS Security Groups will bubble errors from deletion to the top level. Other resources will swallow the error so that it can continue to other resources.

We should:

- Agree on what should happen.
- Make sure all the resources have consistent nuking behavior.
- Implement a feature flag at the top level to toggle between the two behaviors. This should be handled in the main routine, as opposed to the individual nuking functions.

**Comment by ina-stoyanova** [comment]
It seems like there's a few related issues & PRs (traceable through the linked issue above). I'm leaving this one open.

**Comment by hongil0316** [comment]
A lot of the consistency has been addressed as part of the refactoring effort. Will close this issue for now.
