### ISSUE TITLE
Docker version of cloud-nuke

### ISSUE THREAD

**Issue by ghost** [gruntwork-io/cloud-nuke#164]
I would like a dockerized version of cloud-nuke.

I'm planning to run it something like this:

    docker run -it --rm -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN gruntwork-io/cloud-nuke:0.1.24 aws

...thus passing the AWS related environment variable from the current shell into the docker container.

I'm happy to contribute the work and send a PR, if you think this is a good idea

**Comment by brikis98** [comment]
This does seem like a handy thing to have. For the time being, a PR to add a simple `Dockerfile` would be great. We'll eventually want to hook up the CI / CD machinery to publish the `Dockerfile` to a registry on release, but that may have to be added later.

**Comment by sev-obviux** [comment]
Cool, I'll make a PR for just that :)

**Comment by sev-obviux** [comment]
I've created a PR for you: https://github.com/gruntwork-io/cloud-nuke/pull/170
I hope you like it.

**Comment by ina-stoyanova** [comment]
This is still a valid issue. The PR was closed due to inability to devote time and fully test the new features. It can be taken forward, so leaving this issue open.

**Comment by hongil0316** [comment]
No update for the past 2 years. Don't expect this to be prioritized so closing this issue for now. We can reopen this later if we need this in the future.
