### ISSUE TITLE
Tag filtering 

### ISSUE THREAD

**Issue by gastrodon** [gruntwork-io/cloud-nuke#166]
I notice that the only resource that can be preserved with tagging are s3 buckets. Would it be acceptable to patch this tool such that every resource may be deleted / preserved based on some tag's presence, for example a tag `cloud-nuke-excluded` and / or `cloud-nuke-included` to have exclusive / inclusive deleting?

**Comment by brikis98** [comment]
Yes please! [As specified in the docs](https://github.com/gruntwork-io/cloud-nuke#config-file), the config file format, which can do tag filtering, is a relatively recent addition, and we only added support so far for S3. However, we'd love to have it supported for all resources, so a PR to do that is very welcome!

**Comment by ina-stoyanova** [comment]
It seems like this issue has been solved by https://github.com/gruntwork-io/cloud-nuke#config-file and the ability to exclude & include.

**Comment by yorinasub17** [comment]
The config file doesn't support tag based filtering yet (see https://github.com/gruntwork-io/cloud-nuke#whats-supported), so this issue should still be open.

**Comment by lukenny** [comment]
Just wanted to bring it up, it'd be super helpful to have tag based filtering i.e. cloud-nuke-excluded and cloud-nuke-included so we don't have to mess with or rely on the name of the resource.

**Comment by tommy31** [comment]
Hey, same here! 

We would love to have this feature added. Being able to destroy all ressources that does not have one specific tag or have `cloud-nuke-excluded` tag would be such a great feature.

This tool could be the perfect tool to manage developer sandbox at scale.

**Comment by brandon-langley-mf** [comment]
+1 for being able to focus on a tag.   This is particularly helpful when you want to target a terragrunt-based service deployment as opposed to all the resources in the region.

**Comment by hongil0316** [comment]
This feature request has been implemented. Closing this issue.

**Comment by gastrodon** [comment]
Closing the issue for real
