### ISSUE TITLE
Deleting DynamoDB tables

### ISSUE THREAD

**Issue by fredrb** [gruntwork-io/cloud-nuke#167]
I've been using `cloud-nuke` to purge all resources created in test AWS accounts. One of the projects creates a bunch of DynamoDB tables, and I realized that DynamoDB deletion is not supported. 

Is this something you plan to implement? Or is not implemented on purpose? 

Thanks for the project, it's pretty useful. :+1:

**Comment by DMEvanCT** [comment]
I think you can do this by calling list tables api and adding each table to a slice to be deleted. Looking into this.

**Comment by DMEvanCT** [comment]
@fredrb  found out how to do this. Working on the feature now.

**Comment by brikis98** [comment]
A PR to add this is very welcome!

**Comment by lplazas** [comment]
@brikis98 @DMEvanCT  is this something that hasn't been implemented? If so I'd gladly like to have a go at it

**Comment by DMEvanCT** [comment]
I hade a PR for this but there were some requested modifications I have not had time to take a look. Go ahead though!

**Comment by DMEvanCT** [comment]
@fredrb This exists now! Let me know if this solves your problem!

**Comment by infraredgirl** [comment]
Fixed in #169.

**Comment by infraredgirl** [comment]
https://github.com/gruntwork-io/cloud-nuke/releases/tag/v0.5.2
