### ISSUE TITLE
New feature: ability to delete Transit Gateway

### ISSUE THREAD

**Issue by rafaelleonardocruz** [gruntwork-io/cloud-nuke#171]
I've been using `cloud-nuke` to purge all resources created in test AWS accounts. One of the projects creates a bunch of Transit Gateways, and I realized that Transit Gateway deletion is not supported.

I'm opening this issue because I would like to implement this feature.

Thanks for the project, it's pretty useful. +1

**Comment by brikis98** [comment]
+1 on this. PRs are very welcome.

**Comment by rafaelleonardocruz** [comment]
Relesed on [v0.1.26](https://github.com/gruntwork-io/cloud-nuke/releases/tag/v0.1.26)
