### ISSUE TITLE
New feature: ability to delete SQS Queue

### ISSUE THREAD

**Issue by rafaelleonardocruz** [gruntwork-io/cloud-nuke#172]
I've been using `cloud-nuke` to purge all resources created in test AWS accounts. One of the projects creates a bunch of SQS Quee, and I realized that SQS Queue deletion is not supported.

I'm opening this issue because I would like to implement this feature.

Thanks for the project, it's pretty useful. +1

**Comment by brikis98** [comment]
+1 on this. PRs are very welcome.

**Comment by rafaelleonardocruz** [comment]
Release on [v0.1.30](https://github.com/gruntwork-io/cloud-nuke/releases/tag/v0.1.30)
