### ISSUE TITLE
New feature: ability to delete SNS Topic

### ISSUE THREAD

**Issue by rafaelleonardocruz** [gruntwork-io/cloud-nuke#173]
I've been using `cloud-nuke` to purge all resources created in test AWS accounts. One of the projects creates a bunch of SNS Topic, and I realized that SNS Topic deletion is not supported.

I'm opening this issue because I would like to implement this feature.

Thanks for the project, it's pretty useful. +1

**Comment by brikis98** [comment]
+1 on this. PRs are very welcome.
