### ISSUE TITLE
Update cloud-nuke config file to support all existing resources

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/cloud-nuke#176]
We recently added support for configuring `cloud-nuke` via a config file, but this feature only supported a [few of the resources](https://github.com/gruntwork-io/cloud-nuke#whats-supported). We should update `cloud-nuke` to support filtering all other resources via the config file.

**Comment by hongil0316** [comment]
Recently refactored all the resource types to support config file configuration. Closing this issue.
