### ISSUE TITLE
Support for Azure

### ISSUE THREAD

**Issue by sahmed007** [gruntwork-io/cloud-nuke#180]
Hello, are PRs welcome for Azure as well? Or is this tool intended for strictly AWS?

**Comment by brikis98** [comment]
We would love to support Azure in the future, but the truth is that, right now, we don't have the resources to do it. It would mean setting up Azure accounts, new CI / CD pipelines, maintaining lots of extra code, etc, and unfortunately, our small team just doesn't have the capacity for that at the moment.

**Comment by ina-stoyanova** [comment]
Closing this issue, since we can't take any action at this time.
