### ISSUE TITLE
exclude a role when nuking

### ISSUE THREAD

**Issue by rowbot1** [gruntwork-io/cloud-nuke#192]
Hi, grateful if you can provide some guidance on how to exclude a role when nuking an account.

ty

**Comment by brikis98** [comment]
`cloud-nuke` doesn't yet support nuking IAM roles. See https://github.com/gruntwork-io/cloud-nuke/pull/165 for progress.

**Comment by marinalimeira** [comment]
`cloud-nuke` supports nuking IAM roles since https://github.com/gruntwork-io/cloud-nuke/releases/tag/v0.14.0.
