### ISSUE TITLE
Add support for me-south-1, eu-south-1, and af-south-1

### ISSUE THREAD

**Issue by Tzrlk** [gruntwork-io/cloud-nuke#203]
At the moment, running cloud-nuke against any of these regions results in:
```
ERROR: Failed to select regions: Invalid values for region: [[eu-south-1]]
```

**Comment by marinalimeira** [comment]
Is this region enabled in your account? What command are you running?

We try to get all enabled regions within an account. What does `aws ec2 describe-regions` return for you?

**Comment by Tzrlk** [comment]
Good question. I switched over to using aws-nuke, so I'm not sure. Will re-open if I encounter the issue again.
