### ISSUE TITLE
cloud-nuke only delete IAM user resource

### ISSUE THREAD

**Issue by AlexanderWiechert** [gruntwork-io/cloud-nuke#207]
-> % AWS_PROFILE=elastic2ls_stage cloud-nuke aws
[cloud-nuke] INFO[2021-09-15T11:57:49+02:00] The following resource types will be nuked:
[cloud-nuke] INFO[2021-09-15T11:57:49+02:00] - accessanalyzer
[cloud-nuke] INFO[2021-09-15T11:57:49+02:00] - acmpca
[cloud-nuke] INFO[2021-09-15T11:57:49+02:00] - ami
[cloud-nuke] INFO[2021-09-15T11:57:49+02:00] - asg
[cloud-nuke] INFO[2021-09-15T11:57:49+02:00] - ebs
[cloud-nuke] INFO[2021-09-15T11:57:49+02:00] - ec2
[cloud-nuke] INFO[2021-09-15T11:57:49+02:00] - ecscluster
[cloud-nuke] INFO[2021-09-15T11:57:49+02:00] - ecsserv
[cloud-nuke] INFO[2021-09-15T11:57:49+02:00] - eip
[cloud-nuke] INFO[2021-09-15T11:57:49+02:00] - ekscluster
[cloud-nuke] INFO[2021-09-15T11:57:49+02:00] - elb
[cloud-nuke] INFO[2021-09-15T11:57:49+02:00] - elbv2
[cloud-nuke] INFO[2021-09-15T11:57:49+02:00] - iam
[cloud-nuke] INFO[2021-09-15T11:57:49+02:00] - lambda
[cloud-nuke] INFO[2021-09-15T11:57:49+02:00] - lc
[cloud-nuke] INFO[2021-09-15T11:57:49+02:00] - nat-gateway
[cloud-nuke] INFO[2021-09-15T11:57:49+02:00] - rds
[cloud-nuke] INFO[2021-09-15T11:57:49+02:00] - s3
[cloud-nuke] INFO[2021-09-15T11:57:49+02:00] - secretsmanager
[cloud-nuke] INFO[2021-09-15T11:57:49+02:00] - snap
[cloud-nuke] INFO[2021-09-15T11:57:49+02:00] - sqs
[cloud-nuke] INFO[2021-09-15T11:57:49+02:00] - transit-gateway
[cloud-nuke] INFO[2021-09-15T11:57:49+02:00] - transit-gateway-attachment
[cloud-nuke] INFO[2021-09-15T11:57:49+02:00] - transit-gateway-route-table
[cloud-nuke] INFO[2021-09-15T11:57:49+02:00] Retrieving active AWS resources in [eu-north-1, ap-south-1, eu-west-3, eu-west-2, eu-west-1, ap-northeast-3, ap-northeast-2, ap-northeast-1, sa-east-1, ca-central-1, ap-southeast-1, ap-southeast-2, eu-central-1, us-east-1, us-east-2, us-west-1, us-west-2, global]
[cloud-nuke] INFO[2021-09-15T11:57:49+02:00] Checking region [1/18]: eu-north-1
[cloud-nuke] INFO[2021-09-15T11:57:52+02:00] Checking region [2/18]: ap-south-1
[cloud-nuke] INFO[2021-09-15T11:58:01+02:00] Checking region [3/18]: eu-west-3
[cloud-nuke] INFO[2021-09-15T11:58:03+02:00] Checking region [4/18]: eu-west-2
[cloud-nuke] INFO[2021-09-15T11:58:06+02:00] Checking region [5/18]: eu-west-1
[cloud-nuke] INFO[2021-09-15T11:58:10+02:00] Checking region [6/18]: ap-northeast-3
[cloud-nuke] INFO[2021-09-15T11:58:26+02:00] Checking region [7/18]: ap-northeast-2
[cloud-nuke] INFO[2021-09-15T11:58:43+02:00] Checking region [8/18]: ap-northeast-1
[cloud-nuke] INFO[2021-09-15T11:59:01+02:00] Checking region [9/18]: sa-east-1
[cloud-nuke] INFO[2021-09-15T11:59:13+02:00] Checking region [10/18]: ca-central-1
[cloud-nuke] INFO[2021-09-15T11:59:19+02:00] Checking region [11/18]: ap-southeast-1
[cloud-nuke] INFO[2021-09-15T11:59:31+02:00] Checking region [12/18]: ap-southeast-2
[cloud-nuke] INFO[2021-09-15T11:59:48+02:00] Checking region [13/18]: eu-central-1
[cloud-nuke] INFO[2021-09-15T11:59:50+02:00] Checking region [14/18]: us-east-1
[cloud-nuke] INFO[2021-09-15T11:59:58+02:00] Checking region [15/18]: us-east-2
[cloud-nuke] INFO[2021-09-15T12:00:05+02:00] Checking region [16/18]: us-west-1
[cloud-nuke] INFO[2021-09-15T12:00:15+02:00] Checking region [17/18]: us-west-2
[cloud-nuke] INFO[2021-09-15T12:00:26+02:00] Checking region [18/18]: global
[cloud-nuke] INFO[2021-09-15T12:00:26+02:00] The following 1 AWS resources will be nuked:
[cloud-nuke] INFO[2021-09-15T12:00:26+02:00] * iam awiechert global

THE NEXT STEPS ARE DESTRUCTIVE AND COMPLETELY IRREVERSIBLE, PROCEED WITH CAUTION!!!

Are you sure you want to nuke all listed resources? Enter 'nuke' to confirm (or exit with ^C): nuke
[cloud-nuke] INFO[2021-09-15T12:02:34+02:00] Terminating 1 resources in batches
[cloud-nuke] INFO[2021-09-15T12:02:34+02:00] Deleting all IAM Users
[cloud-nuke] INFO[2021-09-15T12:02:34+02:00] Detached Policy arn:aws:iam::aws:policy/AdministratorAccess from User awiechert
[cloud-nuke] INFO[2021-09-15T12:02:34+02:00] Delete Login Profile
[cloud-nuke] INFO[2021-09-15T12:02:35+02:00] Deleted Access Key XXX from user awiechert
[cloud-nuke] INFO[2021-09-15T12:02:35+02:00] Deleted IAM User: awiechert
[cloud-nuke] INFO[2021-09-15T12:02:35+02:00] [OK] 1 IAM User(s) terminated

**Comment by marinalimeira** [comment]
What resources are missing? Can you provide more context?

**Comment by marinalimeira** [comment]
Also, which version of cloud-nuke are you using? You can verify that running

```
cloud-nuke --version
```

**Comment by AlexanderWiechert** [comment]
cloud-nuke version v0.5.0

**Comment by marinalimeira** [comment]
@AlexanderWiechert is this issue still persisting? Were you able to nuke other resources by now?

If it still persists, what kind of resources are in your account that cloud nuke was not able to find?

**Comment by AlexanderWiechert** [comment]
I only was able to delete stuff when I ommit the region flag.
