### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by infraredgirl** [gruntwork-io/cloud-nuke#208]
- [ ] Add table of contents.
- [ ] Move the credentials section to the beginning and make sure it mentions authentication.
- [ ] Sometimes it's necessary to configure MFA token, e.g. to manage IAM resources. Investigate when/why this is the case, and mention it in the credentials section.
- [ ] There are two sections called "Running tests". It's probably enough to stick with the in the Development section, and delete the other. one.
- [ ] Talk about building the binary in the Development section.
- [ ] Mention test timeout in Development section - suggest to run tests with a 1h timeout.

**Comment by hongil0316** [comment]
No update for the past 2 years so closing this comment. 
Also, made quite a bit of improvements on the existing README recently regarding configuration and resources availabilities.
