### ISSUE TITLE
RequestLimitExceeded error when resources are a lot

### ISSUE THREAD

**Issue by tonerdo** [gruntwork-io/cloud-nuke#21]

**Comment by josh-padnick** [comment]
I've hit this as well. It'd be nice to have an exponential backoff retry approach here.

**Comment by josh-padnick** [comment]
Also, it may be worth prioritizing the EC2 Instances and Auto Scaling Groups first. Those are the most expensive, and this way, even if you've got a ton of AMIs -- as many AWS accounts do -- you can at least knock those out.

For example, in my use case, my goal was to clear out all the ASGs. But I kept hitting the AMI limit, which meant the tool isn't really usable for my use case. If I can knock out the ASGs but then it takes a long time on the AMIs, then I've at least achieved my objective.
