### ISSUE TITLE
leverage AWS Cloud Control API

### ISSUE THREAD

**Issue by PatMyron** [gruntwork-io/cloud-nuke#211]
`ListResource` and `DeleteResource` from https://aws.amazon.com/blogs/aws/announcing-aws-cloud-control-api/ seem like an easier way to increase type coverage

**Comment by zackproser** [comment]
Thanks for the suggestion! For what it's worth, we recently did an experiment with cloud-control that is documented here: https://github.com/gruntwork-io/cloud-nuke/issues/337

I'm going to close this ticket out for consolidation purposes, but will leave the linked issue up so we can continue to track the progress of cloud control.
