### ISSUE TITLE
[AWS]  Fails to empty (therefore, subsequently delete) s3 buckets that are used for storing trail data

### ISSUE THREAD

**Issue by avineshwar** [gruntwork-io/cloud-nuke#212]
This is likely if you are not detecting any relationships.

**Comment by infraredgirl** [comment]
Thanks for the bug report! This should definitely be fixed, but I'm not sure when we'll have time to address it. If you would like to submit a PR with a fix, that would be greatly appreciated!

**Comment by ellisonc** [comment]
@hongil0316 I think this issue is likely fixed since the execution order has been changed to have cloudtrail nuked before S3. Can you confirm and close this issue if that is the case?

**Comment by hongil0316** [comment]
Correct. `cloud-nuke` won't be able to detect all the dependency and relationship between resources. Based on certain errors, you might have to change the execution order of deletion running `cloud-nuke` operations multiple times with `--resource_type` filter flag.

**Comment by hongil0316** [comment]
Closing this issue since there have been no activities for the past 2 years.
