### ISSUE TITLE
[AWS] Fails to delete s3 buckets that have bucket policies on

### ISSUE THREAD

**Issue by avineshwar** [gruntwork-io/cloud-nuke#213]

**Comment by infraredgirl** [comment]
Thanks for the bug report! This should definitely be fixed, but I'm not sure when we'll have time to address it. If you would like to submit a PR with a fix, that would be greatly appreciated!

**Comment by denis256** [comment]
Fix included in https://github.com/gruntwork-io/cloud-nuke/releases/tag/v0.11.6
