### ISSUE TITLE
Add a test to ensure CircleCI configs are parsable 

### ISSUE THREAD

**Issue by infraredgirl** [gruntwork-io/cloud-nuke#217]
We've had a situation where a bad CircleCI config has broken the build, and it wasn't caught at PR merge time due to lack of tests. We should add some tests to ensure this does not happen again.

For more context, see #216 and #214.

**Comment by zackproser** [comment]
The circle CI command line interface exposes `circleci config validate <config-path>` to make this simpler.

**Comment by hongil0316** [comment]
`.circleCi/<>.yaml` file is not visible inside the circle test pipeline. So unless someone runs this locally, it won't be possible to included this as part of the automated test pipeline. 

Alternative is to duplicate the file into the test folder but it would be hard to keep both files updated at the same time and it will create potential data discrepancy, which will defeat the whole purpose of config testing.
