### ISSUE TITLE
Go 1.15+ no longer support Darwin 32 bit binaries

### ISSUE THREAD

**Issue by ina-stoyanova** [gruntwork-io/cloud-nuke#220]
[From the Go official release notes:](https://golang.org/doc/go1.15)
```
Darwin
As announced in the Go 1.14 release notes, Go 1.15 requires macOS 10.12 Sierra or later; support for previous versions has been discontinued.

As announced in the Go 1.14 release notes, Go 1.15 drops support for 32-bit binaries on macOS, iOS, iPadOS, watchOS, and tvOS (the darwin/386 and darwin/arm ports). Go continues to support the 64-bit darwin/amd64 and darwin/arm64 ports.
```

**Comment by brikis98** [comment]
Check our other Go repos such as Terragrunt and the history of their CircleCi configs. I believe we updated our `terraform-aws-ci` scripts to no longer build the 32 bit version, but to now build ARM versions, so upgrading should fix it.

**Comment by yorinasub17** [comment]
See this PR from `kubergrunt` for an example targeted diff that implements the above: https://github.com/gruntwork-io/kubergrunt/pull/120

**Comment by yorinasub17** [comment]
Filed https://github.com/gruntwork-io/cloud-nuke/issues/222
