### ISSUE TITLE
Fix tests failing 

### ISSUE THREAD

**Issue by ina-stoyanova** [gruntwork-io/cloud-nuke#227]
Currently a few tests on master are [failing](https://app.circleci.com/pipelines/github/gruntwork-io/cloud-nuke/5287/workflows/61334a04-9d9b-48ac-bbf2-f68116936fa3/jobs/26128):
- [x] TestDeleteFullIamUser (fixed by #255)
- [x] TestListSecretsManagerSecrets (fixed by https://github.com/gruntwork-io/cloud-nuke/pull/259)
- [x] TestTimeFilterExclusionNewlyCreatedSecret (fixed by https://github.com/gruntwork-io/cloud-nuke/pull/259)
- [ ] TestCanNukeAllEcsClustersOlderThan24Hours

**Comment by denis256** [comment]
Test `TestCanNukeAllEcsClustersOlderThan24Hours` seems to pass now

![image](https://user-images.githubusercontent.com/10694338/148781277-b8fd421d-4aff-4534-acf4-233658d85ac1.png)

![image](https://user-images.githubusercontent.com/10694338/148781217-43ec19f5-da6e-4e57-8723-9fbcb2e422ed.png)

**Comment by brikis98** [comment]
Hm, I'm still seeing a lot of flaky tests. Consider the test history on [this branch](https://app.circleci.com/pipelines/github/gruntwork-io/cloud-nuke?branch=bugfix%2Fissue-262&filter=all). I re-ran the tests a bunch of times and got different failures each time:

* `TestDeleteFullIamUser`
* `TestListEIPAddress`
* `TestNukeTransitGatewayVpcAttachment`
* `TestListSecretsManagerSecrets`
* `TestCanListAllOpenSearchDomainsOlderThan24hours`

So I think there's more work to be done to make these tests resilient.

**Comment by hongil0316** [comment]
All the tests have been fixed and refactored. Closing this issue.
