### ISSUE TITLE
Add release notes drafter

### ISSUE THREAD

**Issue by ina-stoyanova** [gruntwork-io/cloud-nuke#229]
It'll be great if we have the release notes drafter here. One requirement would be that it also prompts the Grunt making the release to decide if it's a major or a minor release according to our semver approach & this: https://github.com/gruntwork-io/cloud-nuke/releases/tag/v0.2.0

**Comment by zackproser** [comment]
Discussed live on a call today - we're going to skip this as we've been using the GitHub-native release notes generator with success.
