### ISSUE TITLE
Invalid response on prompt leads to immediate exit.

### ISSUE THREAD

**Issue by josh-padnick** [gruntwork-io/cloud-nuke#26]
Cloud-nuke takes a while to identify all the resources it plans to delete in AWS and the finally displays this prompt:

```
Are you sure you want to nuke all listed resources? Enter 'nuke' to confirm: 
```

I accidentally entered `yes` instead of `nuke`, and the program immediately exited, which means I have to re-scan all AWS resources. Instead catch the error and give the user another chance to enter `nuke`. Also consider advising the user to use `CTRL+C` to cancel.

**Comment by marinalimeira** [comment]
I believe this was solved at #73! Closing the issue.
