### ISSUE TITLE
New feature: support for deletion of SageMaker Notebook Instances

### ISSUE THREAD

**Issue by jvanbuel** [gruntwork-io/cloud-nuke#281]
We heavily make use of SageMaker Notebook Instances for our AWS trainings. I got tired of manually deleting notebooks afterwards, and stumbled upon this project. Really cool, nice work!

Would you be interested in adding this functionality? I cobbled together a PR based on the code of other resources (mainly RDS, which has a very similar API).

**Comment by hongil0316** [comment]
This is now supported. Deleting it.
