### ISSUE TITLE
Unable to delete VPC with active VPC endpoints

### ISSUE THREAD

**Issue by sHesl** [gruntwork-io/cloud-nuke#285]
When attempting to delete a subnet with an active VPC endpoint, I'm seeing failures due to a `DependencyViolation` error, causing the whole VPC to fail to delete.

Sample output from me trying to delete a single VPC with a single subnet which contains 10 VPC endpoints:
```
[cloud-nuke] INFO[2022-03-03T22:00:35Z] Terminating 1 resources in batches
[cloud-nuke] INFO[2022-03-03T22:00:35Z] Deleting all VPCs
[cloud-nuke] INFO[2022-03-03T22:00:35Z] Nuking VPC vpc-01d0f9365b69337c8 in region eu-west-2
[cloud-nuke] INFO[2022-03-03T22:00:36Z] ...no Internet Gateway found
[cloud-nuke] INFO[2022-03-03T22:00:36Z] ...deleting subnet subnet-0d062e6195500ab2c
[cloud-nuke] ERRO[2022-03-03T22:00:36Z] Error cleaning up Subnets for VPC vpc-01d0f9365b69337c8: DependencyViolation: The subnet 'subnet-0d062e6195500ab2c' has dependencies and cannot be deleted.
	status code: 400, request id: c00b3f50-3281-4d51-848e-accac2f54340
[cloud-nuke] ERRO[2022-03-03T22:00:36Z] [Failed] DependencyViolation: The subnet 'subnet-0d062e6195500ab2c' has dependencies and cannot be deleted.
```

Once all the endpoints were deleted, the subnet, and eventually the VPC, were successfully nuked.

Reordering the execution [here](https://github.com/gruntwork-io/cloud-nuke/blob/93652812feb7c4764b984d128b8fe3457247c25b/aws/ec2.go#L397) to put `nukeEndpoints` before `nukeSubnets` should resolve this issue. Correct me if I'm wrong, but I don't think there should be any`DependencyViolation`s introduced by moving the endpoints nuke to be the call immediately before nuking the subnets. 

It also looks like VPC endpoint deletion takes a while, and the subnet deletion won't succeed until these endpoints are  all cleared, so perhaps some polling will be needed to check the endpoints are _actually_ gone before continuing (has something similar been done for other resources?).

If that fix sounds sensible, I'd be happy to put together a PR.

**Comment by tonerdo** [comment]
@sHesl you're welcome to take a stab at it!
