### ISSUE TITLE
ERROR: could not find any enabled regions

### ISSUE THREAD

**Issue by fintaro123** [gruntwork-io/cloud-nuke#286]
Hi Guys!

I made a free account last year and I was planning to use cloud-nuke (via my Windows terminal) to delete all my resources but I got the following message: 

ERROR: could not find any enabled regions

after I enter the command: cloud-nuke aws

I am a completely newbie and I just want to close my free account but it seems so hard..

PS: I made a new user in IAM and added AdministratorAccess.

Could someone help me?

**Comment by denis256** [comment]
Hello,
based on error, `cloud-nuke` failed to describe available AWS regions, it may be an issue with passed credentials 

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html

https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html

**Comment by OvidiuMihalcea** [comment]
It did not work for me on Windows, no matter how I've tried to pass the credentials. It did work on Linux though with a simple aws configure.

**Comment by TheJenious0917** [comment]
I have had the same experience. running from Windows 10 and 11 in pwsh and cmd. Cloud-nuke would not detect the login credential variables and would just fail to connect and discover regions. running on ubuntu or mac and I've had no issues.

**Comment by robbuh** [comment]
Add `aws_region = ap-south-1` (or whatever region) on my aws credential config file works for me

`vi ~/.aws/credentials`

```
[user1]]
aws_access_key_id = my_access_key_id
aws_secret_access_key = my_secret_access_key
aws_region = ap-south-1
```

**Comment by hongil0316** [comment]
Thanks for providing the answer to the original questions. Will close this issue now.
