### ISSUE TITLE
VPC Name filtering checks VPC ID, not VPC Name

### ISSUE THREAD

**Issue by brandonstrohmeyer** [gruntwork-io/cloud-nuke#288]
VPC Name filtering presently checks the VPC ID against the config file `names_regex`:
https://github.com/gruntwork-io/cloud-nuke/blob/fcea10876a9eea1afa79524e4205fda15f406162/aws/ec2_vpc.go#L105-L109

Instead, the Name tag of the VPC should be checked against the regex filter.

**Comment by tonerdo** [comment]
@brandonstrohmeyer the values in the config are what we use to identify the resource within the codebase. Since we display the VPC ID when giving the user the option to confirm nuking, we use the VPC Ids in the config file

**Comment by tonerdo** [comment]
@brandonstrohmeyer based on conversations in #287 you are right and it's my mistake. Let me know if you want to send out a PR to fix this. If not, I'll address it later this week.
