### ISSUE TITLE
Refactor AWS GetAllResources method

### ISSUE THREAD

**Issue by tonerdo** [gruntwork-io/cloud-nuke#29]
The following function is a bit too long: https://github.com/gruntwork-io/cloud-nuke/blob/master/aws/aws.go#L66 and needs to be refactored into a more concise form

**Comment by hongil0316** [comment]
This has been actually completed. Will close this comment. https://www.notion.so/gruntwork/Cloud-Nuke-Restructure-Proposal-845f291e952844ae8b0054ad0e466cfc
