### ISSUE TITLE
Cleanup is not complete.

### ISSUE THREAD

**Issue by ukreddy-erwin** [gruntwork-io/cloud-nuke#296]
I ran the nuke script as below.

`cloud-nuke aws --region us-west-2`

Cleanup is 80% done but it is not deleting below resources.

VPC (Not default, custom one created) and linked routing tables,subnets,etc
Internet gateway (Not default, custom one created)
Elastic IPs

**Comment by ukreddy-erwin** [comment]
Also, any option to filter resources based on a tag in a particular region and delete them?

**Comment by hongil0316** [comment]
Filter based on a tag is now supported in a subset of resources. 
Unsupported resource types won't be deleted as part of the nuke operation unfortunately. 

We welcome PRs to implement nuking behaviour for additional resources.
