### ISSUE TITLE
Feature: Add ability to nuke Kinesis Stream/Firehose

### ISSUE THREAD

**Issue by strongishllama** [gruntwork-io/cloud-nuke#301]
Hey there, I had a quick look and it doesn't look like there is any support for nuking Kinesis resources (specifically streams and firehose are what I'm after).

If this is something you'd be okay with accepting a pull request for, I'm happy to work on it.

Cheers!

**Comment by denis256** [comment]
Hi,
yes, removal of Kinesis resources is not implemented yet - feel free to raise PR with support for it :)

**Comment by denis256** [comment]
Added support in release https://github.com/gruntwork-io/cloud-nuke/releases/tag/v0.16.0
