### ISSUE TITLE
How to Delete by account 

### ISSUE THREAD

**Issue by mdemarco1234** [gruntwork-io/cloud-nuke#306]
I did not see an option to delete by an account name.  Are resources deleted in the account logged into or can you Delete from another account. We have an audit account and want to specify which account to delete resources from. can this be done? If so how?

**Comment by denis256** [comment]
Hi,
removal of `IAMUsers` is documented in https://github.com/gruntwork-io/cloud-nuke/blob/master/README.md#example

**Comment by hongil0316** [comment]
No further action here for the past year so closing this issue.
