### ISSUE TITLE
ECS resources are not nuked

### ISSUE THREAD

**Issue by sarkis** [gruntwork-io/cloud-nuke#32]
Resources like ECSCluster, Tasks, Services should all be nuked.

**Comment by sarkis** [comment]
@brikis98 would love to implement this one. Won't commit until I have the time for it, though :)

**Comment by tonerdo** [comment]
@sarkis, go for it! 👍

**Comment by sarkis** [comment]
Just tested #36 and it works perfect. ECS Cluster deletion issue is a non-issue in terms of cloud-nuke and documented - marking this issue as closed. Thanks @yorinasub17!
