### ISSUE TITLE
No assets uploaded to v0.13.0 release

### ISSUE THREAD

**Issue by jbpratt** [gruntwork-io/cloud-nuke#331]
Hi, it appears there have been no build assets uploaded to the latest release https://github.com/gruntwork-io/cloud-nuke/releases/tag/v0.13.0 like previous releases https://github.com/gruntwork-io/cloud-nuke/releases/tag/v0.12.3 

cc @zackproser as the one performing the release

**Comment by jbpratt** [comment]
closing as the latest release as assets tied to it :smiley_cat: thanks for the silent fix!

**Comment by zackproser** [comment]
@jbpratt Yes, there's a delay each time we cut a new release as our job to build and attach cross-platform binaries completes a few minutes later.

**Comment by jbpratt** [comment]
@zackproser for what its worth, it must have failed for the v0.13.0 release https://github.com/gruntwork-io/cloud-nuke/releases/tag/v0.13.0

**Comment by zackproser** [comment]
> @zackproser for what its worth, it must have failed for the v0.13.0 release https://github.com/gruntwork-io/cloud-nuke/releases/tag/v0.13.0

@jbpratt Roger, thanks for the report!
