### ISSUE TITLE
Add ability to use non-default profile

### ISSUE THREAD

**Issue by asokolsky** [gruntwork-io/cloud-nuke#334]
From what I understand, `cloud-nuke` currently uses `default` aws profile.
It would be nice to have this fact documented.
I rely on multiple accounts to structure AWS resources.
It would be much appreciated if `cloud-nuke` would support command line options similar to `aws` to
[specify profile](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html), e.g.
`cloud-nuke --profile foo-bar aws`

**Comment by yorinasub17** [comment]
This is currently not supported via CLI option, but open to a PR to add it in! With that said, see https://github.com/gruntwork-io/cloud-nuke/issues/49 for workaround.

**Comment by hongil0316** [comment]
Closing this issue as we have answer for this already.
