### ISSUE TITLE
Improve messaging when there is no downloaded binary

### ISSUE THREAD

**Issue by pete0emerson** [gruntwork-io/cloud-nuke#342]
In #338 I neglected to add the `v` to my version when specifying `--tag 0.16.2`.

The messaging should be improved; in other words, if there is no tag, then we should not see the message that I saw:

`Moving /tmp/gruntwork-script-modules/cloud-nuke_darwin_amd64 to /usr/local/bin/cloud-nuke and setting execute permissions`

This is misleading, because moving insinuates that the binary actually exists.

Can we detect the existence of the tag, and show something like:

`There is no tag 0.16.2`?

**Comment by yorinasub17** [comment]
I think this is more an issue for `gruntwork-install` (and probably `fetch`?), so we should move it there!

**Comment by pete0emerson** [comment]
Ah, yes, that's right. I'll move it.

**Comment by pete0emerson** [comment]
Tracked [here](https://github.com/gruntwork-io/gruntwork-installer/issues/79)
