### ISSUE TITLE
Cloud-nuke not accurately inspecting and deleting all API Gateways (v1 and v2) in an AWS account

### ISSUE THREAD

**Issue by sapenteng** [gruntwork-io/cloud-nuke#367]
I've been trying to use cloud-nuke to delete API Gateways, However, it's not properly identifying these resources. I had over 200 APis in an account in one region to be deleted, but CN only identified 24 in that region. Is this a behavior anyone has noticed? Not sure what I'm missing. Any ideas will be much appreciated. Thank you.
`cloud-nuke inspect-aws --resource-type apigateway --resource-type apigatewayv2`

**Comment by hongil0316** [comment]
Hello @sapenteng, can you share more details about the issue you've faced? 
Can you run your command with `log-level=debug` to see more information? 

Gateways should not be filtered unless you specified time & name regex filter.

**Comment by hongil0316** [comment]
Haven't heard back for a while. WIll close this issue now but reach out if you have any other questions.
