### ISSUE TITLE
cloud-nuke rate exceeded errors

### ISSUE THREAD

**Issue by denis256** [gruntwork-io/cloud-nuke#371]
Noticed that `cloud-nuke` periodically fails on removal of IAM Roles
```
...
[cloud-nuke] INFO[2022-10-30T21:15:14Z] Deleting all IAM Roles in region eu-north-1 
...
[cloud-nuke] INFO[2022-10-30T21:15:15Z] Detached Policy arn:aws:iam::aws:policy/XYZ from Role cloud-nuke-TestNukeEksClusters-kv1nIl 
[cloud-nuke] INFO[2022-10-30T21:15:15Z] Detached Policy arn:aws:iam::aws:policy/XYZ from Role cloud-nuke-TestNukeEksClusters-OjXBGV 
[cloud-nuke] INFO[2022-10-30T21:15:15Z] Detached Policy arn:aws:iam::aws:policy/XYZ from Role cloud-nuke-TestNukeEksClusters-rm5C21 
[cloud-nuke] ERRO[2022-10-30T21:15:19Z] [Failed] 1 error occurred:
	* Throttling: Rate exceeded
	status code: 400, request id: 5946b7f8-0df3-4c78-8f4f-6be090c0d88a
 
[cloud-nuke] ERRO[2022-10-30T21:15:19Z] [Failed] 1 error occurred:
	* Throttling: Rate exceeded
	status code: 400, request id: a928fdd0-68ff-474b-8445-200e31efd1c3
 
ERROR: 2 errors occurred:
	* Throttling: Rate exceeded
	status code: 400, request id: 5946b7f8-0df3-4c78-8f4f-6be090c0d88a
	* Throttling: Rate exceeded
	status code: 400, request id: a928fdd0-68ff-474b-8445-200e31efd1c3

```

**Comment by zackproser** [comment]
Wonder if we should consider implementing similar functionality here that [we put into git-xargs](https://github.com/gruntwork-io/git-xargs/pull/67/files) to address the same problem, but with GitHub's API. 

There might be a simpler way / package, too.

**Comment by ellisonc** [comment]
Ran into issues with this as well deleting policies from iam groups

**Comment by pete0emerson** [comment]
AWS isn't terribly straightforward about their rate limiting. Basically, they say "you can investigate to find out which calls are being rate limited"

https://aws.amazon.com/premiumsupport/knowledge-center/cloudtrail-rate-exceeded/

Some more links:

https://aws.amazon.com/premiumsupport/knowledge-center/autoscaling-api-calls-throttled/

https://docs.aws.amazon.com/general/latest/gr/api-retries.html

https://bobcares.com/blog/aws-api-throttling-rate-exceeded/

https://stackoverflow.com/questions/62294399/getting-throttlingexception-rate-exceeded-status-code-400-on-aws-api

**Comment by hongil0316** [comment]
This should no longer be an issue since we changed all the unit tests to use mocks, instead of doing actual creation & deletion.
