### ISSUE TITLE
Feature Request: protect resources from deletion based on a tag

### ISSUE THREAD

**Issue by kjhosein** [gruntwork-io/cloud-nuke#38]
_Example use case:_
Let's say you have a sandbox/dev account and want to use `cloud-nuke` to keep it clean of old artifacts, but on the other hand have resources that you're actively using and that may also be even older than your time threshold. 

_Solution:_ 
Tag those resources with something like `'cloud-nuke'='protect'`

**Comment by SeanFarrow** [comment]
@brikis98,

I'd be happy to work on this, as it's something that would be really useful and I have a bit of spare time.

A couple of questions though:
Should we have a separate method to nuke included/excluded tagged resources rather than using the existing one?
What sorts of tests would you want for this? I know you are running builds using circle CI so wonder what you do about creating/tearing down resources.

**Comment by brikis98** [comment]
> Should we have a separate method to nuke included/excluded tagged resources rather than using the existing one?

Not sure I follow what you're referring to by "method." Do you mean a separate top-level CLI command? Or separate Go method? 

> What sorts of tests would you want for this? I know you are running builds using circle CI so wonder what you do about creating/tearing down resources.

Probably a test that launches a few resources, some with tags, some without, and makes sure cloud-nuke with various tag parameters cleans up the right ones.

**Comment by SeanFarrow** [comment]
I mean a separate go method for nuking tagged resources.

**Comment by brikis98** [comment]
> I mean a separate go method for nuking tagged resources.

I'd be tempted to say it makes sense to update the existing methods to take tags into account as well, as it should be possible to specify tags *and* other params (e.g., creation date).

**Comment by SeanFarrow** [comment]
I agree, let me get a PR done in the next few days.

**Comment by brikis98** [comment]
Thank you!

**Comment by mastertinner** [comment]
Has there been any progress on this? I'd love to see the tag whitelist.

**Comment by SeanFarrow** [comment]
Nothing has happened currently, I am in the process of a big house move, but will get to this when settled.

**Comment by rmarable** [comment]
Has there been any update to this enhancement request?

**Comment by SeanFarrow** [comment]
Not as yet, but there will be after Christmas.
I now have some time and need it for a project.
Thanks,
Sean.

**Comment by aaronsteers** [comment]
I started a PR which would allow inclusion and exclusion by a tag. 

Contributions and feedback welcome: #109

**Comment by hongil0316** [comment]
Similar issue https://github.com/gruntwork-io/cloud-nuke/issues/166. WIll close this one and continue the conversation in this issue - https://github.com/gruntwork-io/cloud-nuke/issues/166
