### ISSUE TITLE
Removal of dedicated hosts

### ISSUE THREAD

**Issue by denis256** [gruntwork-io/cloud-nuke#380]
Noticed that `cloud-nuke` is not removing EC2 dedicated hosts, having removal of these resources will be a good reduction of AWS account bills

**Comment by hongil0316** [comment]
This enhancement request is in progress by @arsci

**Comment by zackproser** [comment]
@denis256 Looks like we have [full support for EC2 dedicated hosts](https://github.com/gruntwork-io/cloud-nuke/blob/master/aws/ec2_dedicated_host.go#L17) in the codebase already - did you mean the removal is failing?

**Comment by denis256** [comment]
Was implemented as part of: https://github.com/gruntwork-io/cloud-nuke/pull/392
