### ISSUE TITLE
BUG: "cloud-nuke aws --resource-type rds" doesn't only delete RDS DBs but also deletes documentDBs

### ISSUE THREAD

**Issue by sapenteng** [gruntwork-io/cloud-nuke#389]
Hi team, I've noticed a bug with the cli command `cloud-nuke aws --resource-type rds` that seem to affect DocumentDB clusters. Not sure why but I ended up nuking my docdb clusters whilst running that command hoping to only target rds. Hopefully it can be looked into. Thank you.

**Comment by ellisonc** [comment]
@sapenteng thanks for bringing this to our attention. I agree that doesn't seem like desired behavior.  Looking under the hood it seems the RDS apis also support interacting with Document and Neptune db which at least explains why this is happening. We will be going on break for 2 weeks starting Mon, Dec 19 but I will add this to our backlog for the new year.  In the mean time a PR would be welcome or you can use the config Yaml file with regular expressions to filter out any databases you want to keep around

**Comment by zackproser** [comment]
Thanks @sapenteng and @ellisonc. 

I see that we're using the [DescribeDBInstances](https://docs.aws.amazon.com/sdk-for-go/api/service/rds/#RDS.DescribeDBInstances) method when listing instances for any cloud-nuke user who passes the `--resource-type` value of `rds`. 

However, this method supports accepting a set of filters in its input struct. It looks like we could pare down results returned to only those that have an engine type of `docdb`, like so: 

```
package main

import (
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/service/rds"
)

func main() {
	sess := session.Must(session.NewSessionWithOptions(session.Options{
		SharedConfigState: session.SharedConfigEnable,
	}))

	svc := rds.New(sess)

	// Create a new Input struct with a filter for Engine = "docdb"
	input := &rds.DescribeDBInstancesInput{
		Filters: []*rds.Filter{
			{
				Name:   aws.String("engine"),
				Values: []*string{aws.String("docdb")},
			},
		},
	}

	// Call the DescribeDBInstances API endpoint
	result, err := svc.DescribeDBInstances(input)
	if err != nil {
		fmt.Println(err)
		return
	}

	// The result.DBInstances field will now only contain DocumentDB instances
	fmt.Println(result.DBInstances)
}
```
Still thinking through the best UX for supporting this, however. Throwing out a couple initial thoughts: 

1. Keep the `rds` resource type as it is, and consider additional flags that would essentially allow you to specify these filters when targeting the `rds` resource type
2. Split the `rds` resource type out into discrete resource types, one for each class of data store under the RDS umbrella. There's plenty of downsides to doing this - including trying to keep up with AWS releases in the future.
3. Wide open for better suggestions

In the interim, definitely use the config file workaround that @ellisonc proposed - and we'll be adding a note to our README to call out this important caveat in the meantime.
