### ISSUE TITLE
VPC not getting deleted

### ISSUE THREAD

**Issue by RagunathAnbarasu** [gruntwork-io/cloud-nuke#395]
I am using cloud nuke v0.11.8

Cloud nuke is unable to remove VPC, it shows the following error.
![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/44649428/213252610-3a15f7ef-368e-4508-9df8-35d58b222e6f.png)

In CLI it shows there is dependency upon security groups, I have checked the console and there were no dependencies to delete security group. It might be possible that there is interdependency between two security groups that doesn't allow VPC to get deleted.

However, I am able to delete the same VPC using the AWS console but not through cloud nuke.

**Comment by ellisonc** [comment]
We've made significant changes to the VPC dependency handling in the most recent version of cloud-nuke.  Could you try using the latest version v0.22.1

**Comment by hongil0316** [comment]
Recently submitted quite a lot of changes that should address the VPC dependency violation error. Can you try with the latest change? 

Closing this issue as we've not heard back for quite some time. Feel free to raise another ticket if you continue to experience issues.
