### ISSUE TITLE
I have added --exclude-resource-type iam in the nuke command but still see lot of Iam resorces are getting delted.

### ISSUE THREAD

**Issue by sreenusuuda** [gruntwork-io/cloud-nuke#406]
I see below Iam resources are getting deleted even after adding '--exclude-resource-type iam ' to the command.

Is it bug or I am doing any thing wrong?

Is there any way I can exclude entire IAM stuff including roles, polices etc.

<img width="409" alt="Screenshot 2023-02-03 at 12 46 30 PM" src="https://user-images.githubusercontent.com/99465779/216536973-de7ff3fc-2f60-491d-9e5a-27ee91a813dd.png">

**Comment by ellisonc** [comment]
Hi @sreenusuuda the `iam` type refers to IAM Users. IAM roles, groups, and policies have their own resource type tags. try adding `--exclude-resource-type iam-role`, `--exclude-resource-type iam-group` and `--exclude-resource-type iam-policy` to your command
