### ISSUE TITLE
Cloud nuke not deleting Elasticache parameter groups and subnet groups

### ISSUE THREAD

**Issue by RagunathAnbarasu** [gruntwork-io/cloud-nuke#414]
I am using cloud-nuke version v0.20.0 to cleanup a region.

While deleting Elasticache clusters, cloud nuke is not deleting the Elasticache parameter groups and subnet groups.

**Comment by ellisonc** [comment]
Hi @RagunathAnbarasu thanks for letting us know.  I remember seeing a problem recently with elasticache parameter groups on the newer versions.  Can you let me know what parameter group family it was trying to delete and I'll try to reproduce the issue.  Also is any error message provided? or does it silently fail to remove them?

**Comment by RagunathAnbarasu** [comment]
The parameter group family in my case is - redis7
It silently fail to remove it.

**Comment by boldandbusted** [comment]
Not sure if this is related, but I'm seeing cloud-nuke leaving behind database subnet groups. Thanks for cloud-nuke! :)
