### ISSUE TITLE
cloud-nuke gcp

### ISSUE THREAD

**Issue by acrisci** [gruntwork-io/cloud-nuke#42]
Hi,

I'm interested in using cloud-nuke for google cloud platform. I see it on the roadmap in the README. Are you accepting contributions for this feature?

**Comment by josh-padnick** [comment]
We'd love contributions for GCP or any other cloud! We use the name `cloud-nuke` because we wantd to add other clouds, but we just haven't gotten around to it yet.

**Comment by wyardley** [comment]
Might make some sense to look at doing this via Magic Modules:
https://github.com/GoogleCloudPlatform/magic-modules
since a lot of the scaffolding (and information needed) is already there.

**Comment by wyardley** [comment]
@josh-padnick I can take a look at what’s involved.

**Comment by sjmiller609** [comment]
Also relevant - a gcloud CLI feature to list all resources. https://cloud.google.com/sdk/gcloud/reference/alpha/resources/list

**Comment by koalalorenzo** [comment]
Is anybody looking/working on this?

**Comment by acrisci** [comment]
I'm not working on it. Look at #45.

**Comment by arehmandev** [comment]
I wrote something rather quick in case anyone wants a look: https://github.com/arehmandev/gcp-nuke - happy for any contributors

**Comment by hongil0316** [comment]
Closing this issue as there seems to be other open source tools that tackle this problem and there are no immediate plans to implement this feature in cloud-nuke
