### ISSUE TITLE
API gateway removal does not remove client certificates 

### ISSUE THREAD

**Issue by RagunathAnbarasu** [gruntwork-io/cloud-nuke#428]
While the API gateway is nuked it remove the API, but the Client Certificates attached to the API are not removed.
Unfortunately the client certificates keep accumulating if the same API is redeployed.
I am using cloud nuke v0.20.0

**Comment by denmanveer** [comment]
hello team, is there any update on this? We are part of MicroFocus (Paid client), and we wanted to know the status so that we can decide if we want to do it at our end or contribute directly to Cloud Nuke or use the different version which addresses this already. thank you.

**Comment by ellisonc** [comment]
@denmanveer thanks for reaching out.  We don't have a fix scheduled for this right now, but I will add it to our backlog. We'd welcome a PR if you have the time.

**Comment by denmanveer** [comment]
> @denmanveer thanks for reaching out. We don't have a fix scheduled for this right now, but I will add it to our backlog. We'd welcome a PR if you have the time.

thank you so much @ellisonc for the reply, this helps, to understand this is a bug, not a version issue.
Definitely will try to contribute directly if time persists.
