### ISSUE TITLE
S3 buckets are n't getting cleaned up and access points are n't deleted while nuking s3 bucket

### ISSUE THREAD

**Issue by abhishekmahajan0709222** [gruntwork-io/cloud-nuke#442]
While the S3 bucket is nuked it gave error that s3 buckets are n't getting cleaned up and access points are n't getting deleted
I am using cloud nuke v0.29.0

**Comment by hongil0316** [comment]
There's an open PR but it would require quite a lot of work to rebase - https://github.com/gruntwork-io/cloud-nuke/pull/450. Posting this in case someone picks up the work in the future.
