### ISSUE TITLE
Use cloud-nuke as library to delete resources

### ISSUE THREAD

**Issue by abhishekmahajan0709222** [gruntwork-io/cloud-nuke#461]
Is it possible to nuke resources in the same way as it if we use as library in golang code

**Comment by robpickerill** [comment]
Hi, yes, the readme provides instructions:
https://github.com/gruntwork-io/cloud-nuke#using-cloud-nuke-as-a-library

You can also find API documentation:
https://pkg.go.dev/github.com/gruntwork-io/cloud-nuke

**Comment by hongil0316** [comment]
Closing this issue if there are no further questions on this.
