### ISSUE TITLE
Not able to nuke eks cluster

### ISSUE THREAD

**Issue by abhishekmahajan0709222** [gruntwork-io/cloud-nuke#465]
Its mention in the documentation that cloud-nuke version(0.29.0) supports eke cluster but when we try to run it was n't able to delete and keeps on trying
Kubernetes version : 1.23
Issue : Fargate profile got stuck in creating status

<img width="1235" alt="image" src="https://github.com/gruntwork-io/cloud-nuke/assets/126277188/c2844c3c-9de5-4507-a3cb-5232c6a09ab1">

**Comment by abhishekmahajan0709222** [comment]
As we are paid customer to the gruntworks

Can you please look into the issue and provide solutions ASAP?
Thanks

**Comment by hongil0316** [comment]
Hey @abhishekmahajan0709222, from the screenshot alone, it's quite hard to understand what's happening. Can you elaborate more about the error you encountered? 

Also, how would you reproduce this issue?

**Comment by hongil0316** [comment]
Closing this issue as there has been no response back on this issue for quite some time. Please reach out if you still have problems.
