### ISSUE TITLE
aw transit-gateway-attachment should check nukable before describing

### ISSUE THREAD

**Issue by kate-syberspace** [gruntwork-io/cloud-nuke#478]
## Summary:
I'm using a very scoped IAM role to do my nuking, and only want to delete s3 resources. [Here](https://github.com/gruntwork-io/cloud-nuke/blob/06207d0f88713ba2fafacfd6d50bba5a80b6f78f/aws/aws.go#L430) it would be nice to check `IsNukeable(transitGatewayVpcAttachments.ResourceName(), resourceTypes)` before running the `DescribeTransitGateways` to avoid seeing the error below.

## Command:
```
AWS_PROFILE=${my_profile} AWS_REGION=${my-region} DISABLE_TELEMETRY=TRUE cloud-nuke aws \
  --resource-type s3  \
  --region "${my_region}" \
  --config "${config}" \
  --older-than 336h \
```

## Error:
```
\| ResourceType               \| Description                         \| Error                                                                                                                                      \|
--
  | \| transit-gateway-attachment \| Unable to retrieve Transit Gateways \| UnauthorizedOperation: You are not authorized to perform this operation.                                                                   \|
  | \| 	status code: 403, request id: 0270f379-8325-45c5-a4e7-b0ecf3b177ed

```

**Comment by hongil0316** [comment]
Thanks for reporting this issue. Hey @kate-syberspace, would you be able to put up a PR with a fix?
