### ISSUE TITLE
--older-than ignored for SNS topics

### ISSUE THREAD

**Issue by flichtenheld** [gruntwork-io/cloud-nuke#480]
AFAICT --older-than is completely ignored for SNS topics, cloud-nuke just wants to delete all of them.

I'm using this command line:

    cloud-nuke aws --dry-run --region=$REGION --older-than 24h --exclude-resource-type ami --exclude-resource-type snap --exclude-resource-type cloudtrail

Related to #359 ?

 I have updated to v0.31.2 to verify that the issue still exists in the latest version.

**Comment by robpickerill** [comment]
I naively thought that SNS APIs would give me the create time in the get-topic-attributes API: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sns@v1.17.13#GetTopicAttributesOutput. 

It looks like none of the APIs provide the create timestamps for SNS topics, which if true, would mean that it may be impossible to filter sns topics by creation time.

**Comment by robpickerill** [comment]
I added: https://github.com/gruntwork-io/cloud-nuke/pull/482 which supports include/exclude of the SNS topic by name, but for the --older-than I'm not able to find any API support for the creation time of a topic. If anyone does know of a way, let me know and I will update the PR.

**Comment by flichtenheld** [comment]
Yeah, some resources in AWS don't have creation time. But cloud-nuke already has an established mechanism for that: It sets a tag when it first sees the resource, and will only delete when that tag is older than what is given with `--older-than`. I think VPCs are an example of that.

**Comment by robpickerill** [comment]
Thanks, I read through the VPC code, and that would be easy to implement, let me update the PR.

**Comment by robpickerill** [comment]
Added time exclusions in #482. Needs some reviews then you should be good to go.

**Comment by robpickerill** [comment]
#482 was merged, all being well this issue can be closed

**Comment by hongil0316** [comment]
Oh nice. Closing this.
