### ISSUE TITLE
Still trying to delete default Elasticache Subnet Group while running cloud-nuke aws

### ISSUE THREAD

**Issue by abhishekmahajan0709222** [gruntwork-io/cloud-nuke#486]
Hello team

Cloud nuke version : 0.31.0

It tries to delete default  Elasticache Subnet Group when I am simply try to run cloud-nuke aws command
<img width="816" alt="image" src="https://github.com/gruntwork-io/cloud-nuke/assets/126277188/e485648e-d726-48a0-8e29-26de63f3c599">

**Comment by hongil0316** [comment]
Hey @abhishekmahajan0709222, just to make sure I understand the issue correctly. When you run 

```
cloud-nuke aws
```

It tries to delete your Elasticcache Subnet Group? It didn't show any confirmation prompt before proceeding the deletion? 

The expected behaviour is the following
> Simply running cloud-nuke aws will start the process of cleaning up your cloud account. You'll be shown a list of resources that'll be deleted as well as a prompt to confirm before any deletion actually takes place.

**Comment by abhishekmahajan0709222** [comment]
@hongil0316 The issue we have is cloud nuke tries to delete default value of Elasticache subnet group, that results in failure

Is there any way to exclude default resource for deletion?

If yes can you please share the doc link ?
