### ISSUE TITLE
Nuke VPC endpoint services

### ISSUE THREAD

**Issue by wjam** [gruntwork-io/cloud-nuke#54]
VPC endpoint services, not VPC endpoints directly, as they may be fronting NLBs spun up during testing. As part of deleting the VPC endpoint services, any existing endpoint connections would need to be rejected.

My reasoning for not targeting VPC endpoints is that, in my case, they are potentially tied into how the VPC is designed - such as allowing communication to AWS APIs without going onto the big-wide internet

**Comment by hongil0316** [comment]
Hey @wjam, do you want to create a PR for this request? Otherwise, I'll close this comment as there's no other votes on this particular request.

**Comment by hongil0316** [comment]
Closing this issue as we've had no interaction on this for a while.
