### ISSUE TITLE
Add ability to nuke specific regions

### ISSUE THREAD

**Issue by saady** [gruntwork-io/cloud-nuke#55]
Instead of passing all the regions to the exclude-region flag, we need to add a flag to specify a list of regions to be nuked.

**Comment by rraiatsysgain** [comment]
+1

**Comment by saurabh-hirani** [comment]
@autero1 This can be closed as it is addressed by https://github.com/gruntwork-io/cloud-nuke/pull/71 in the latest release.

**Comment by autero1** [comment]
Closing in favor of #71
