### ISSUE TITLE
Nuke VPCs and related resources

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/cloud-nuke#57]
A nice to have (but not critical) for the future would be the ability to nuke VPCs and all related resources:

- The VPC itself
- Subnets
- Route tables
- NACLs
- VPC endpoints
- NAT Gateways
- ENIs / EIPs

**Comment by andrewalvintran** [comment]
I am interested in working on this and I created some files to delete the VPC itself, but of course if there are resources associated with the VPC, then you must delete them first or the VPC cannot be deleted.  What would be the general approach for nuking the resources associated with the VPC? 

Should you first nuke all of the VPC related resources individually, and then nuke the VPC?

**Comment by brikis98** [comment]
> Should you first nuke all of the VPC related resources individually, and then nuke the VPC?

Yup! Probably need to delete subnets, route tables, peering connections, and VPC endpoints first.

**Comment by ekristen** [comment]
I would like to see this implemented ASAP and I'm happy to help, would it be preferred to re-use the same code used for the default vps or would it be better to implement like the rest of the resources all individually and in the right order?

**Comment by bwhaley** [comment]
Hi @ekristen - thanks for offering to help! You should be able to reuse the functionality of [`NukeVpcs()`](https://github.com/gruntwork-io/cloud-nuke/blob/aeff0d3b982810af3bb634ef93d083d06ea9fed6/aws/ec2.go#L394) which deletes all the stuff in the correct order already. Just call it with different inputs.

**Comment by ekristen** [comment]
@bwhaley https://github.com/gruntwork-io/cloud-nuke/pull/243

**Comment by bwhaley** [comment]
Fixed in #243. Thanks to @ekristen.
