### ISSUE TITLE
Nicer logs for CI executions

### ISSUE THREAD

**Issue by carldjohnston** [gruntwork-io/cloud-nuke#572]
Good morning wonderful gruntworkers,

We are nuking our test environments with cloud-nuke, running from a github action, which is working nicely.

Unfortunately we see 1000's of lines of output from the "Retrieving active AWS resources" message spinner in our actions log. https://github.com/gruntwork-io/cloud-nuke/blob/2d031b4772b0c5c2827d552b5455fb3e97ed21fd/commands/cli.go#L296

<img width="2047" alt="image" src="https://github.com/gruntwork-io/cloud-nuke/assets/10494326/45212b5f-4b70-42cb-a8c5-acaf35d7f946">

Is there a way we could disable the spinner, or get a simpler output mode for use in automation?

Thank you!

Carl

**Comment by ellisonc** [comment]
We've also found this annoying internally and have plans to add a flag to enable a more machine-readable output. No ETA yet unfortunately. That being said, PRs are always welcome!

**Comment by carldjohnston** [comment]
Thank you @hongil0316 ❤️
