### ISSUE TITLE
How to schedule / use cloud-nuke non-interactive?

### ISSUE THREAD

**Issue by fex01** [gruntwork-io/cloud-nuke#603]
Sorry for the complete noob question - but how do I use cloud-nuke non-interactive? How to skip the _type nuke to really delete everything_-dialog?

As far as I understand it, a large part of the value in cloud-nuke is the ability to schedule runs to make really sure that all resources in the test env got deleted? But either I'm overlooking something or neither the `--help` output nor the README is mentioning how to run cloud-nuke unsupervised?

**Comment by hongil0316** [comment]
I believe `--force` is the flag you are looking for. https://github.com/gruntwork-io/cloud-nuke/blob/master/commands/cli.go#L83. 

Did you try running `cloud-nuke aws --help` command?

**Comment by fex01** [comment]
> I believe `--force` is the flag you are looking for.

Perfect - that's exactly what I was looking for 👍 

> Did you try running `cloud-nuke aws --help` command?

Oh, that's the trick 😳 I did run `cloud-nuke --help` without the `aws`  addendum - which was not very helpful 😅

**Comment by hongil0316** [comment]
Glad it worked for you 👍
