### ISSUE TITLE
Migrate Go from 1.18 to 1.21

### ISSUE THREAD

**Issue by khareyash05** [gruntwork-io/cloud-nuke#611]
I would like to migrate Go from 1.18 to 1.21 as 1.18 has reached EOL. Reference [https://endoflife.date/go](https://endoflife.date/go)

**Comment by hongil0316** [comment]
Yeah for sure. Thanks for flagging this. Here is the PR for it - https://github.com/gruntwork-io/cloud-nuke/pull/612
