### ISSUE TITLE
Need intro-for-dummies

### ISSUE THREAD

**Issue by Alan-R** [gruntwork-io/cloud-nuke#626]
I have an AWS account, which I haven't accessed in many years, but has resources I get billed for.

What I did to set it up was done years ago, and I don't remember what I did to set it up, and it wasn't set up on any computer that still exists.

When I run it on Linux, I get this message:

```
$ DISABLE_TELEMETRY=true ./cloud-nuke_linux_amd64 inspect-aws
ERRO[2023-12-02T18:39:57-07:00] Error forming a cloud-nuke Query with supplied parameters. Original error: Unable to determine enabled regions in target account. Original error: could not find any enabled regions  binary=cloud-nuke version=v0.33.0
```

I suspect this is because it has no idea who I am, nor what AWS account to use. 
A little hint on what to do to get started (install this, run that..., create this file) would be helpful. Or at least a list of prerequisites.

**Comment by hongil0316** [comment]
Hello @Alan-R, did you get a chance to read through the README file to use this CLI tool?

**Comment by hongil0316** [comment]
Closing this as we haven't heard anything for the past 2 weeks.

**Comment by vestedpr-dev** [comment]
Hi -- I think their point is valid: I don't see anything in the README that documents how your tool connects to AWS. I assume it's via the `aws` command line tool, but it would not hurt to state this explicitly and just link off to the required tool and list the prerequisites.
