### ISSUE TITLE
programmatically example not working

### ISSUE THREAD

**Issue by Gabryel8818** [gruntwork-io/cloud-nuke#634]
Using example not working https://github.com/gruntwork-io/cloud-nuke?tab=readme-ov-file#using-cloud-nuke-as-a-library

imports following the documentation:
![image](https://github.com/gruntwork-io/cloud-nuke/assets/50804183/2b1679da-6e7f-4b1b-9d06-1e40d65f4b41)

linter error:
![image](https://github.com/gruntwork-io/cloud-nuke/assets/50804183/7b0ec762-c61e-4cdc-991f-00f35099a51b)

run error:
![image](https://github.com/gruntwork-io/cloud-nuke/assets/50804183/ca4b6edd-09ea-46cf-9470-91614f26f9c3)

go version go1.21.5 linux/amd64
Kernel: Linux 6.6.6-arch1-1
OS: EndeavourOS

**Comment by matheusquintinostone** [comment]
Im facing the same issue here =/

**Comment by hongil0316** [comment]
fixed the documentation. Please try it out again - https://github.com/gruntwork-io/cloud-nuke/pull/637
