### ISSUE TITLE
Ability to delete specific resources instead of all

### ISSUE THREAD

**Issue by saurabh-hirani** [gruntwork-io/cloud-nuke#64]
cloud-nuke is great for cleaning up stale resources and saving $$. I wanted to run an idea through the team to know if this makes sense.

The current cli for cloud-nuke is 

``` 
cloud-nuke aws
```

which when run gets all active AWS resources and then deletes them. This could be explicity called out by making the user specify an "all" argument e.g. 

```
cloud-nuke aws all 
```

will delete all the supported resources. This means that the user can delete either all of the supported resources or specific ones by specifying

```
cloud-nuke aws ec2
```

which will delete only ec2 instances. The advantage of doing so are:

1. Reducing search time.
2. Targeting specific resources as someone might not want entire account deletion but only for specific components. 
3. Giving the user an ability to list out the currently supported resources from the cmdline instead of referring to the README.

**Comment by brikis98** [comment]
Seems like a great addition. Only thing I'm not sure about is if the UX should be 

```
cloud-nuke <CLOUD> [<RESOURCE_TYPE]...]

# example
cloud-nuke aws ec2
``` 

or 

```
cloud-nuke <CLOUD> [--resource <RESOURCE_TYPE>...]

# example
cloud-nuke aws --resource ec2
```

The latter is longer, but I suspect clearer and more extensible.

**Comment by brikis98** [comment]
Oh, and either way, PR welcome to add this!

**Comment by saurabh-hirani** [comment]
Thanks @brikis98  - To add to the UX point - I think it is a question of whether we want it to be an argument or an option. 

If it is an argument

```
cloud-nuke aws ec2 
cloud-nuke aws s3
cloud-nuke aws all
```

would make it more explicit to the end user that it is a mandatory input. With an option, the usage would be 

```
cloud-nuke aws --resource ec2
cloud-nuke aws --resource s3
cloud-nuke aws 
```

If ``` cloud-nuke aws ``` means that nuke all - then I think it is a little dangerous. However if we make the option mandatory (contradictory use of words :)) we could say that you have to pass the --resource option, which now that I think of it also has the advantage of having multiple values 

```
cloud-nuke aws --resource ec2 --resource s3 
```

can support multiple resources. So - to take best of both the worlds - have ``` --resource ``` as mandatory would help in making the intention explicit and be extensible for multiple resources instead of one.

**Comment by saurabh-hirani** [comment]
> Oh, and either way, PR welcome to add this!

Sure - will give it a shot.

**Comment by saurabh-hirani** [comment]
@brikis98 raised PR - https://github.com/gruntwork-io/cloud-nuke/pull/65

**Comment by autero1** [comment]
Closing
#65
