### ISSUE TITLE
Unit Test Failures in Cloud-Nuke CircleCi

### ISSUE THREAD

**Issue by hongil0316** [gruntwork-io/cloud-nuke#666]
Seeing errors in circleCi Test Pipeline

```
Fatal error: concurrent map writes
=== CONT  TestEgressOnlyInternetGateway_GetAll/timeAfterExclusionFilter
```

We should be able to just get rid of "t.Parallel()" to avoid issue like this. Since we are mocking everything, `t.Parallel()` shouldn't really affect performance too much. Otherwise, we would have to change the structure of the test quite a lot or introduce locking in the code base.

**Comment by hongil0316** [comment]
Hi @denis256, thinking of just getting rid of `t.Parallel()` in test cases. WDYT?

**Comment by hongil0316** [comment]
I believe `t.Parallel()` should fix the issue. If that doesn't fix it, we can explore other options. When users are using the `cloud-nuke`, there shouldn't be any scenario where any resource update the map variable concurrently because we usually update that when all the results are available.

**Comment by hongil0316** [comment]
It seems like the error is happening when we are updating `Nukables map[string]error` in the `BaseAwsResource`. 
We can definitely put mutex lock around it but since it only happens for test scenarios, I'm a bid redundant to modify code to pass test cases. I would prefer to remove `t.Parallel()` instead.

**Comment by denis256** [comment]
Eliminating `t.Parallel()` might appear as a straightforward solution, but it will hide the issue with parallel access which may appear in the future if it is decided to implement concurrent removal.

We can go the quick route now - remove `t.Parallel()` and add another issue to fix concurrent access to the map.

Looking at the last tests - it is not failing, or affected resources weren't present in AWS or it is not failing each time?

**Comment by hongil0316** [comment]
Hey @denis, when that use case arise, I think it will be a pretty simple fix to introduce mutex.Lock in the BaseResource when updating the map.
