### ISSUE TITLE
Delete Lambda functions

### ISSUE THREAD

**Issue by mastertinner** [gruntwork-io/cloud-nuke#67]
It would be awesome if we could delete Lambda functions based on their tags and age.

**Comment by andreybleme** [comment]
Hey guys, I want to help with this but I have some questions on how are we supposed to handle it... The lambda function details returned by the SDK [only includes](https://docs.aws.amazon.com/sdk-for-go/api/service/lambda/#Lambda.GetFunction) the `LastModified` date (and tags). 

I'm not sure if it would be clever to assume that the flag `--older-than 24h` relies on this `LastModified` lambda date.
What do you guys think? I'd like some input here before start working on this issue with this tricky assumption :)
@yorinasub17 @marinalimeira

**Comment by brikis98** [comment]
Yup, I think `LastModified` date would work just fine!

**Comment by marinalimeira** [comment]
This has been implemented at #134
