### ISSUE TITLE
EIP timestamp parsing error

### ISSUE THREAD

**Issue by ellisonc** [gruntwork-io/cloud-nuke#670]
Encountered a bug retrieving EIPs, the timestamp for one appeared to be in an unexpected format causing the entire resource list process to fail for eips.

`Unable to retrieve eip, parsing time "2023-11-14 17:40:32" as "2006-01-02T15:04:05Z07:00": cannot parse " 17:40:32" as "T"`

**Comment by sbocinec** [comment]
I've experienced the same error with the latest `cloud-nuke` version `0.35.0`:
`ERROR   Unable to retrieve eip, parsing time "2023-12-19 10:34:26" as "2006-01-02T15:04:05Z07:00": cannot parse " 10:34:26" as "T"`

**Comment by sbocinec** [comment]
I've created a quick fix proposal for this issue https://github.com/gruntwork-io/cloud-nuke/pull/678
