### ISSUE TITLE
Option to not add 'cloud-nuke-first-seen' tag

### ISSUE THREAD

**Issue by mpahlrothanton** [gruntwork-io/cloud-nuke#675]
Hi!

Would it be possible to add a CLI flag to not add the 'cloud-nuke-first-seen' tag on inspected resources?

For example;
when I just want to do a **cloud-nuke --dry-run** or **cloud-nuke inspect-aws**, I don't necessarily want to change any resources, ie. not add any tags to existing resource.

Otherwise I need to either remove the tags, or add ignore policy to our IaC tooling, eg. Terraform ignore_changes lifecycle policy.

Thanks in advance!

**Comment by tiagoliveira9** [comment]
Is this option already available? @hongil0316 
Because I still get this tag added with a `cloud-nuke --dry-run` or `cloud-nuke inspect-aws` and then breaks my terraform code.

**Comment by hongil0316** [comment]
Should be available now. Can you try passing in `exclude-first-seen` flag when running those commands?

**Comment by tiagoliveira9** [comment]
@hongil0316  I think your PR was merged after the last release v0.35.0 April 8. If I run `cloud-nuke inspect-aws --exclude-first-seen` it complains, `flag provided but not defined: -exclude-first-seen  binary=cloud-nuke version=v0.35.0`. If I run `cloud-nuke inspect-aws exclude-first-seen`, it runs but it adds tags the same.
Can you provide instructions to compile locally? Or when trigger a new release?

**Comment by hongil0316** [comment]
Just released a new version. Do you want to try again? [https://github.com/gruntwork-io/cloud-nuke/releases/tag/v0.36.0](https://github.com/gruntwork-io/cloud-nuke/releases/tag/v0.36.0)

**Comment by tiagoliveira9** [comment]
@hongil0316 Thanks, I did tried but when the flag is enabled is dies
```
Searching eip resources in eu-west-1 (1m50s)ERRO[2024-05-23T10:09:37+01:00] runtime error: invalid memory address or nil pointer dereference  binary=cloud-nuke version=v0.36.0
```
