### ISSUE TITLE
Test roles are leaking

### ISSUE THREAD

**Issue by Etiene** [gruntwork-io/cloud-nuke#68]
Iam roles created on automated tests for this repo are not getting properly deleted and are accumulating inside our test AWS account.

**Comment by queglay** [comment]
I would also like to be able to delete IAM roles, groups, and users since terraform can generate these., it would be handy indeed to nuke them.

**Comment by arsci** [comment]
Closing this issue as these features have been implemented

IAM service linked roles in release v0.26.0 PR #415 
IAM roles in release v0.14.0 PR #330 
IAM groups in release v0.21.2 PR #364 
IAM users PR #131 

See also #116
