### ISSUE TITLE
Feature request - delete resource in a specific region

### ISSUE THREAD

**Issue by mrrajeshrai** [gruntwork-io/cloud-nuke#70]
Hi Team,

Are you planning to add include-region flag anytime soon? which can be used to delete resources in a specific region. 

Thanks

**Comment by autero1** [comment]
Hi @mrrajeshrai, I believe this is a duplicate of #55, so closing this. A PR would be very welcome!

**Comment by saurabh-hirani** [comment]
@autero1 @mrrajeshrai - raised https://github.com/gruntwork-io/cloud-nuke/pull/71 for the above.
