### ISSUE TITLE
Runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by TheOutsSeeker** [gruntwork-io/cloud-nuke#732]
Running the latest version of cloud-nuke v0.36.0 with the parameter crashes. 

AWS_PROFILE=<Your-AWS-Profile> cloud-nuke inspect-aws --exclude-first-seen, throws in my case the following error message after ~7+ mins.

"Searching eip resources in eu-central-1 (7m12s)ERRO[2024-07-01T15:19:19+01:00] runtime error: invalid memory address or nil pointer dereference  binary=cloud-nuke version=v0.36.0"

Tested it on ARM & AMD x86_64 macOS v14.4.1.

Excluding the EIP resource from scans avoids the exception. 

AWS_PROFILE=<Your-AWS-Profile> cloud-nuke inspect-aws --exclude-first-seen --exclude-resource-type eip

**Comment by james03160927** [comment]
Hi @TheOutsSeeker, I cannot reproduce the same issue on the newest release. Can you try out using the new release? https://github.com/gruntwork-io/cloud-nuke/releases/tag/v0.37.0

**Comment by TheOutsSeeker** [comment]
Yes, of course - I will get back to you.

**Comment by TheOutsSeeker** [comment]
The binaries aren't available here: https://github.com/gruntwork-io/cloud-nuke/releases/tag/v0.37.0 for download yet

**Comment by james03160927** [comment]
Can you try with this one? https://github.com/gruntwork-io/cloud-nuke/releases/tag/v0.37.1

**Comment by TheOutsSeeker** [comment]
Thanks. With the latest version I can't reproduce the issue anymore either.

**Comment by TheOutsSeeker** [comment]
Thanks.
