### ISSUE TITLE
Contribution guideline should highlight dependency on dep, or update to go modules to simplify onboarding

### ISSUE THREAD

**Issue by saurabh-hirani** [gruntwork-io/cloud-nuke#77]
While debugging https://github.com/gruntwork-io/cloud-nuke/issues/49 with @sugandh-pasricha - setting up a local environment to get cloud-nuke code gave the following error:

```
go get -v github.com/gruntwork-io/cloud-nuke
github.com/gruntwork-io/cloud-nuke/commands
# github.com/gruntwork-io/cloud-nuke/commands
commands/cli.go:22:5: app.Author undefined (type *cli.App has no field or method Author)
commands/cli.go:25:15: cannot use []cli.Command literal (type []cli.Command) as type []*cli.Command in assignment
commands/cli.go:31:24: cannot use cli.StringSliceFlag literal (type cli.StringSliceFlag) as type cli.Flag in array or slice literal:
        cli.StringSliceFlag does not implement cli.Flag (Apply method has pointer receiver)
commands/cli.go:35:24: cannot use cli.StringSliceFlag literal (type cli.StringSliceFlag) as type cli.Flag in array or slice literal:
        cli.StringSliceFlag does not implement cli.Flag (Apply method has pointer receiver)
commands/cli.go:39:24: cannot use cli.StringSliceFlag literal (type cli.StringSliceFlag) as type cli.Flag in array or slice literal:
        cli.StringSliceFlag does not implement cli.Flag (Apply method has pointer receiver)
commands/cli.go:43:17: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
        cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
commands/cli.go:47:19: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
        cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
commands/cli.go:52:17: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
        cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
commands/cli.go:62:17: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
        cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
```

I also tried and can confirm that  ``` go get github.com/gruntwork-io/cloud-nuke ``` gives this error. This failure is because doing a ```go get``` gets github.com/urfav/cli which has a breaking change

```
~/go/src/github.com/urfave/cli# git describe --tags
v1.22.1-335-g0587424
```

because the pinned version is v1.20.0 as per https://github.com/gruntwork-io/cloud-nuke/blob/master/Gopkg.toml#L30

So if one wants to do local development they should **ignore** the above error and then go to the downloaded folder and do the following

```
cd gruntwork-io/cloudnuke
dep ensure -v
go build
```
which creates a local vendor folder.

Is there a way to ensure that ```go get github.com/gruntwork-io/cloud-nuke``` does not give the above error and gets the right versions of modules?

If not then we should have a "How to contribute" section in the README calling this out.

**Comment by yorinasub17** [comment]
`cloud-nuke` uses `dep` to manage dependencies and does not support `go get` since it hasn't been updated to use go modules yet. The steps of using `dep ensure` is the right way to do this, although you are right that this should be clear in the contribution guidelines.

PRs to update docs, or to migrate to `go modules` are both welcome!

**Comment by saurabh-hirani** [comment]
@yorinasub17 raised https://github.com/gruntwork-io/cloud-nuke/pull/79 for the same.

**Comment by robmorgan** [comment]
fixed in https://github.com/gruntwork-io/cloud-nuke/pull/79
