### ISSUE TITLE
Migrate to AWS SDKv2

### ISSUE THREAD

**Issue by james03160927** [gruntwork-io/cloud-nuke#770]
The AWS SDK v1 is officially deprecated (end-of-support is July 31, 2025). We need to migrate code to v2 before it ends the support for this.

**Comment by sc250024** [comment]
@james03160927 Is EC2 being covered by someone? If not, then I think a new issue just for that would be nice. It's a much larger refactor.

**Comment by sc250024** [comment]
@james03160927 @wakeful Is EC2 being covered by someone? If not, then I think a new issue just for that would be nice. It's a much larger refactor. I would be happy to do it, but along the way, I would have some questions about how it's desired to be structured.

**Comment by wakeful** [comment]
@sc250024 You can pick the ec2 resource. AFAIK, there is some reference between ec2 resources and VPC (and actually all other network-related ones). Just ping on this issue to let us know what you'll be working on to avoid duplication. I’ll look over the weekend for any remaining resources that need a 'bump'.

**Comment by sc250024** [comment]
@wakeful I will open a new issue then. The reason is because I started down the rabbit hole with `internet-gateway` and `egress-only-internet-gateway` before realizing that EC2, VPC, Subnets, etc. are all interconnected somehow.

**Comment by james03160927** [comment]
Re-opening this as there a couple more PRs to complete.
