### ISSUE TITLE
Please include a sample configuration file

### ISSUE THREAD

**Issue by stefan-nordcloud** [gruntwork-io/cloud-nuke#786]
Hey guys,

Great product you're providing 👍 One suggestion I have to make life for new users somewhat easier, is to include a sample configuration file.

For example, I find [this tag-filer](https://github.com/gruntwork-io/cloud-nuke/blob/master/README.md?plain=1#L527-L536) incomprehensible. Where is the value `true` defined? Or does that just meant that a tag with the key "foo" is present, regardless of its value?

I think it would help a few of us (see https://github.com/gruntwork-io/cloud-nuke/issues/631).

Maybe something like config_simple.yaml and config_advanced.yaml for example?

**Comment by stefan-nordcloud** [comment]
Thanks for merging that PR 👍 As far as I'm concerned, this issue can be closed now but I'll let you two sort that out 😉

**Comment by james03160927** [comment]
It seems like there's some issue with the automation. We will close the issue shortly! cc: @odgrim
