### ISSUE TITLE
Limit defaults-aws to security groups only

### ISSUE THREAD

**Issue by jmorsecode** [gruntwork-io/cloud-nuke#80]
In the case of default VPCs that are still in use, a user should still be able to remediate for CIS by blanking the default security groups. An option on defaults-aws to exclude VPC destruction would allow this.  Currently I do not see any AWS CIS requirements for removing all default VPCs. Only that the default security group restricts all traffic and others do not openly allow RDP or SSH.

**Comment by bwhaley** [comment]
Added this in [v0.1.13](https://github.com/gruntwork-io/cloud-nuke/releases/tag/v0.1.13). 🎉
