### ISSUE TITLE
Add region excludes to defaults-aws

### ISSUE THREAD

**Issue by jmorsecode** [gruntwork-io/cloud-nuke#81]
In the case that 90% of the regions are unused but need to be CIS remediated before being disabled completely, it would help greatly to be able to nuke default-aws --exclude-region X in similar fashion to the standard nuke aws. Then at most the in use region can be manually remediated for CIS afterwards.

**Comment by bwhaley** [comment]
Added this in [v0.1.13](https://github.com/gruntwork-io/cloud-nuke/releases/tag/v0.1.13). 🎉
