### ISSUE TITLE
I can't exclude VPC with cloud-nuke-excluded tag or any other

### ISSUE THREAD

**Issue by ErezWeiss** [gruntwork-io/cloud-nuke#810]
I tried to exclude VPC by tagging it with cloud-nuke-excluded tag, but it doesn't work.

**Comment by wakeful** [comment]
hey @ErezWeiss,

Thank you for highlighting this issue. I believe the `documentation` is unclear.
The `cloud-nuke-excluded` tag is supported only on resources that have a ✅ in the `tags` column.

This should be resolved by #811.

**Comment by ErezWeiss** [comment]
thanks!!
