### ISSUE TITLE
Delete all AWS resources in an account based on a specific tag?

### ISSUE THREAD

**Issue by Muru-777** [gruntwork-io/cloud-nuke#813]
I am trying to delete all AWS resources in an account based on a specific tag (e.g., tag:release-environment with value val-157373). Is it possible to achieve this using a global filter in cloud-nuke, or is there a similar feature available?

**Comment by wakeful** [comment]
hey,

`cloud-nuke` does not support filtering resources by `global tag`. You need to create a config file specifying a tag filter for each resource you want to delete. Also, not every resource supports `tag filtering`. You can see the [list here](https://github.com/gruntwork-io/cloud-nuke/blob/master/README.md#whats-supported).

**Comment by james03160927** [comment]
Thanks @wakeful for the answer. Will close this issue.
