### ISSUE TITLE
A new version request

### ISSUE THREAD

**Issue by ErezWeiss** [gruntwork-io/cloud-nuke#816]
Hi guys
There hasn't been a release since last August... When will a version be published?

Erez

**Comment by sc250024** [comment]
I can't say for sure 100%, but I suspect shortly after this PR is merged: https://github.com/gruntwork-io/cloud-nuke/pull/804

**Comment by denis256** [comment]
Hi,
recently was released cloud-nuke with the usage of AWS SDK v2, you can try it on your environment to check how it will work

https://github.com/gruntwork-io/cloud-nuke/releases/tag/v0.38.0
