### ISSUE TITLE
Feature Request: Exclude Resources by Tag Existence

### ISSUE THREAD

**Issue by ErezWeiss** [gruntwork-io/cloud-nuke#822]
### Feature Request: Exclude Resources by Tag Existence in Cloud Nuke

**Current Behavior:**
Cloud Nuke currently supports excluding resources based on a specified key only if its value is `"true"`.

**Feature Request:**
Add support for excluding resources based on the existence of a tag key, regardless of its value.

**Use Case:**
For example, if a resource has the tag `Component: rds`, I would like to exclude it by specifying `isTagExist: Component`. This ensures that all resources with the key `Component` (regardless of its value) are excluded from nuking.

**Proposed Solution:**
Introduce a new parameter `isTagExist` that accepts a tag key. If the specified key exists on a resource, the resource will be excluded.

**Benefits:**
- Provides more flexibility for users to manage exclusions.
- Simplifies scenarios where values of tags are dynamic or irrelevant.

**Example Configuration:**
```yaml
excludeTags:
  isTagExist: Component
```

Would exclude any resource with the tag `Component` present, such as:
- `Component: rds`
- `Component: database`
- `Component: test`

Let me know if more details are needed!

**Comment by wakeful** [comment]
hey, @ErezWeiss 

Just to clarify your request: should that exclusion be a global filter (applied across all resources), or are you looking for the possibility to set this per `resource`, e.g.?

```yaml
s3:
  exclude:
    ifTagExist: Component
```

**Comment by ErezWeiss** [comment]
@wakeful 
Hey!
Per resource would be preferable.
So we can exclude EC2 of EKS, and EBS of a specific cluster, etc.

**Comment by james03160927** [comment]
Hi @ErezWeiss, could you please provide more context on why the existing configuration approach cannot be used to exclude certain resources from the nuking operation?

**Comment by ErezWeiss** [comment]
Hi @wakeful,  
Thank you for your commits—I really appreciate the effort!  
I just wanted to note that in our scenario, we’re aiming to filter by a tag’s key regardless of its value. I noticed that your code checks for an empty value, but in our case, there is a value present, and we’d like to ignore it altogether.  

Thanks again for your work! 😊

**Comment by james03160927** [comment]
Got it. Left an additional comment on the PR.

**Comment by ErezWeiss** [comment]
@james03160927 thanks!
