### ISSUE TITLE
Move to go modules

### ISSUE THREAD

**Issue by chenrui333** [gruntwork-io/cloud-nuke#90]
Right now go is with go 1.13.6, many repos have been moved to go modules which is the future go toolchain. So suggesting move this repo to also use go modules and deprecate `dep`.

**Comment by brikis98** [comment]
+1 on this. PR to do this is very welcome!

**Comment by koalalorenzo** [comment]
Should this be closed? 🤔

**Comment by chenrui333** [comment]
yeah, it can be closed now. thanks for the reminder. :)
