### ISSUE TITLE
Support deleting Amazon Managed Streaming for Apache Kafka (Amazon MSK)

### ISSUE THREAD

**Issue by jrgwv** [gruntwork-io/cloud-nuke#93]
Please consider supporting deleting MSK clusters when nuking a region. An MSK cluster does have a tag attribute so it could be filtered out if needed.

**Comment by brikis98** [comment]
We are not currently using MSK, so we're not likely to get to this, but PRs to add support are very welcome!

**Comment by hongil0316** [comment]
MSK cluster resource has been added in the past. Will close this issue.
