### ISSUE TITLE
Support deletion of cloudformation stacks

### ISSUE THREAD

**Issue by andreamaruccia** [gruntwork-io/cloud-nuke#95]
Would be nice to be able to delete cloudformation stacks older than x days

**Comment by brikis98** [comment]
Seems like a reasonable feature request, but we don't make much use of CloudFormation here, so we're not likely to get to this any time soon. PRs welcome.

**Comment by ekristen** [comment]
@brikis98 I'm looking at submitting a PR to solve this. There are stack and stack sets and sets can contain stacks, would you all rather there be a type like `cf-stackset` and `cf-stack` and just ensure we delete all sets before stacks or would you all rather it be implemented like the VPC nuke code where we just know X resources have to be nuked before the VPC can finally be deleted? 

It's possible to delete stacks without stacksets only if the sets don't refer to the stacks being deleted.

**Comment by hongil0316** [comment]
Closing this PR as we've not made any changes or updates since 2021.
